"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,BriefcaseBusiness,ChevronDown,CircleDollarSign,ClipboardCheck,FlaskConical,Gauge,Home,Landmark,LockKeyhole,Search,Settings,ShieldCheck,ShoppingCart,Target,UserRound,UsersRound} from "lucide-react";

type Group={name:string;icon:any;items:string[]}; type Row=Record<string,any>;
const groups:Group[]=[
{name:"Executive",icon:Gauge,items:["Executive Overview","Portfolio Analytics","Pipeline Analytics"]},
{name:"Pre-Award",icon:Target,items:["Opportunity Intelligence","Eligibility & Fit","Applications","Proposal Workspace","Budget Builder","Internal Review","Approvals","Submissions"]},
{name:"Award Management",icon:BriefcaseBusiness,items:["Award Register","Award Setup","Contracts & Agreements","Partners & Subawards","Due Diligence","Amendments","Deliverables","Risks & Issues"]},
{name:"Finance & Accounts",icon:CircleDollarSign,items:["Finance Dashboard","Award Budgets","Funds Received","Expenditure","Commitments","Budget vs Actual","Partner Advances","Financial Reporting","Financial Forecasts","Reconciliations","Financial Approvals","Financial Closeout"]},
{name:"Procurement",icon:ShoppingCart,items:["Procurement Dashboard","Procurement Plans","Requisitions","Purchase Orders","Suppliers & Due Diligence","Procurement Contracts","Equipment & Assets","Procurement Tracking"]},
{name:"Laboratory",icon:FlaskConical,items:["Laboratory Oversight","Laboratory Procurement","Reagents & Consumables","Laboratory Equipment","Maintenance & Calibration","Laboratory Compliance"]},
{name:"Research Governance",icon:ShieldCheck,items:["Ethics & Regulatory Links","Conflicts / Declarations","Compliance Calendar","Privacy & Information Governance","Legal & Contracts Review"]},
{name:"Performance",icon:BarChart3,items:["Reports","Outputs","Impact","Closeout"]},
{name:"People & Organisation",icon:UsersRound,items:["Researcher Profiles","Partner Directory","Funder Directory","NHRC Institutional Profile"]},
{name:"Personal",icon:UserRound,items:["My Work","Notifications","Calendar"]},
{name:"Administration",icon:Settings,items:["Users & Roles","Organisation Structure","Approval Rules","Delegations & Acting Roles","Workflow Configuration","Forms & Fields","Reference Data","Templates","Notification Rules","Calendar Rules","Data Import & Export","Records & Archives","Access Reviews","Help & Support","Audit Log","System Settings"]},
{name:"IT & Security",icon:LockKeyhole,items:["System Health","Service Monitoring","Integration Health","Job Monitor","Backup & Recovery","Security Centre","Security Events","Privileged Activity","Business Continuity","Environment Management","Superadmin Console"]}
];
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8080";
const endpoints:Record<string,string>={
"Opportunity Intelligence":"/api/opportunities","Eligibility & Fit":"/api/opportunities","Applications":"/api/applications","Proposal Workspace":"/api/applications","Budget Builder":"/api/applications","Internal Review":"/api/applications","Submissions":"/api/applications","Award Register":"/api/awards","Award Setup":"/api/awards","Finance Dashboard":"/api/finance/summary","Award Budgets":"/api/awards","Funds Received":"/api/finance/receipts","Requisitions":"/api/procurement/requisitions","Laboratory Oversight":"/api/laboratory/items","Reagents & Consumables":"/api/laboratory/items?type=REAGENT","Laboratory Equipment":"/api/laboratory/items?type=EQUIPMENT","Users & Roles":"/api/admin/users","Audit Log":"/api/admin/audit","Security Events":"/api/operations/system-events","Backup & Recovery":"/api/operations/backups"};

export default function HomePage(){const[open,setOpen]=useState<string|null>(null),[active,setActive]=useState("Home"),[summary,setSummary]=useState<Row|null>(null),[query,setQuery]=useState(""); useEffect(()=>{fetch(`${api}/api/dashboard/summary`).then(r=>r.ok?r.json():null).then(setSummary).catch(()=>setSummary(null))},[]); const selected=useMemo(()=>groups.find(g=>g.items.includes(active)),[active]); const choose=(g:string,i:string)=>{setOpen(g);setActive(i);setQuery("")}; return <div className="appShell"><aside className="sidebar"><button className="brand" onClick={()=>{setActive("Home");setOpen(null)}}><div className="logo">NHRC</div><div><b>NHRC Grants</b><span>Research Funding Lifecycle</span></div></button><nav><button className={`home ${active==="Home"?"active":""}`} onClick={()=>{setActive("Home");setOpen(null)}}><Home size={17}/>Home</button>{groups.map(g=>{const I=g.icon,e=open===g.name,a=selected?.name===g.name;return <div className={`group ${a?"groupActive":""}`} key={g.name}><button className="groupBtn" onClick={()=>setOpen(e?null:g.name)}><I size={18}/><span>{g.name}</span><ChevronDown className={e?"rotate":""} size={15}/></button>{e&&<div className="items">{g.items.map(i=><button key={i} className={active===i?"active":""} onClick={()=>choose(g.name,i)}>{i}</button>)}</div>}</div>})}</nav></aside><main><header><div><span className="eyebrow">NAVRONGO HEALTH RESEARCH CENTRE</span><h1>{active==="Home"?"Grant Management Platform":active}</h1></div><div className="topActions"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this workspace"/></div><span className="env">UAT / DEVELOPMENT</span></div></header>{active==="Home"?<Landing summary={summary} openArea={(g,i)=>choose(g,i)}/>:<Workspace name={active} group={selected?.name||""} query={query}/>}</main></div>}

function Landing({summary,openArea}:{summary:Row|null;openArea:(g:string,i:string)=>void}){return <div className="content"><section className="hero"><div><span className="pill">Institutional research funding lifecycle</span><h2>One governed workspace for NHRC grants</h2><p>Discover opportunities, develop proposals, govern approvals, manage awards, finances, procurement, laboratory obligations, compliance, reporting and institutional closeout.</p><div className="heroActions"><button onClick={()=>openArea("Executive","Executive Overview")}>Open Executive Overview</button><button className="secondary" onClick={()=>openArea("Personal","My Work")}>Open My Work</button></div></div><Landmark size={74}/></section><div className="metrics"><Metric label="Opportunities" value={summary?.opportunities}/><Metric label="Applications" value={summary?.applications}/><Metric label="Active awards" value={summary?.activeAwards}/><Metric label="Pending approvals" value={summary?.pendingApprovals}/><Metric label="Reports due" value={summary?.reportsDue}/><Metric label="Open risks" value={summary?.openRisks}/></div><section><div className="sectionTitle"><div><span className="eyebrow">FUNCTIONAL AREAS</span><h3>Institutional workspaces</h3></div></div><div className="cards">{groups.map(g=>{const I=g.icon;return <button className="areaCard" key={g.name} onClick={()=>openArea(g.name,g.items[0])}><div className="cardIcon"><I/></div><h4>{g.name}</h4><p>{g.items.slice(0,4).join(" · ")}{g.items.length>4?" · …":""}</p><span>Open workspace →</span></button>})}</div></section></div>}
function Metric({label,value}:{label:string,value:any}){return <div className="metric"><span>{label}</span><strong>{value??"—"}</strong></div>}

function Workspace({name,group,query}:{name:string;group:string;query:string}){const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[status,setStatus]=useState(""),[selected,setSelected]=useState<Row|null>(null); const endpoint=endpoints[name]||fallback(group,name); useEffect(()=>{setSelected(null); if(!endpoint){setData(null);return} setLoading(true); const sep=endpoint.includes("?")?"&":"?"; const url=`${api}${endpoint}${query?`${sep}q=${encodeURIComponent(query)}`:""}${status?`${query?"&":sep}status=${encodeURIComponent(status)}`:""}`; fetch(url).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(setData).catch(e=>setData({error:e.message})).finally(()=>setLoading(false))},[name,query,status,endpoint]); const rows=Array.isArray(data)?data:[]; return <div className="content"><section className="workspaceHead"><div><span className="eyebrow">{group.toUpperCase()}</span><h2>{name}</h2><p>{endpoint?"Live records from the governed NHRC Grants database.":"Configured v0.7 workspace. Transaction screens are activated progressively against the approved workflow."}</p></div><button className="primary">New / Add record</button></section><div className="filterbar"><div className="search wide"><Search size={16}/><input value={query} readOnly placeholder="Search"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>OPEN</option><option>ACTIVE</option><option>PENDING</option><option>COMPLETED</option></select><button onClick={()=>setStatus("")}>Clear filters</button></div>{loading?<div className="panel">Loading records…</div>:data?.error?<div className="panel error">Unable to load this workspace: {data.error}</div>:!endpoint?<ModuleSummary name={name} group={group}/>:Array.isArray(data)?<Register rows={rows} onSelect={setSelected}/>:<SummaryObject data={data}/>} {selected&&<DetailDrawer row={selected} close={()=>setSelected(null)}/>}</div>}
function fallback(group:string,name:string){if(group==="Executive")return "/api/dashboard/summary";if(group==="Award Management")return "/api/awards";if(group==="Finance & Accounts")return "/api/finance/summary";if(group==="Procurement")return "/api/procurement/requisitions";if(group==="Laboratory")return "/api/laboratory/items";return ""}
function Register({rows,onSelect}:{rows:Row[];onSelect:(r:Row)=>void}){if(!rows.length)return <div className="empty"><ClipboardCheck size={34}/><h3>No matching records</h3><p>Change the filters or create the first governed record for this workspace.</p></div>; const preferred=["reference","title","name","funder","stage","status","eligibility_status","deadline_at","currency","total_award","amount","display_name","roles"]; const keys=preferred.filter(k=>rows.some(r=>r[k]!==undefined)).slice(0,7); return <div className="tableWrap"><table><thead><tr>{keys.map(k=><th key={k}>{pretty(k)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} onClick={()=>onSelect(r)}>{keys.map(k=><td key={k}>{format(r[k],k)}</td>)}</tr>)}</tbody></table></div>}
function SummaryObject({data}:{data:Row}){return <div className="summaryGrid">{Object.entries(data).map(([k,v])=><div className="summaryTile" key={k}><span>{pretty(k)}</span><strong>{format(v,k)}</strong></div>)}</div>}
function DetailDrawer({row,close}:{row:Row;close:()=>void}){return <div className="drawerBackdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>Close</button><span className="eyebrow">RECORD DETAIL</span><h3>{row.title||row.name||row.reference||"Record"}</h3>{Object.entries(row).map(([k,v])=><div className="detail" key={k}><span>{pretty(k)}</span><b>{format(v,k)}</b></div>)}</aside></div>}
function ModuleSummary({name,group}:{name:string;group:string}){return <div className="empty"><ClipboardCheck size={34}/><h3>{name}</h3><p>{group} is part of the approved institutional architecture. Its controls, permissions and underlying records are present in the platform foundation and its dedicated transaction view is being activated against those governed services.</p></div>}
function pretty(k:string){return k.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())} function format(v:any,k:string){if(v===null||v===undefined||v==="")return "—"; if(typeof v==="number"&&/(amount|award|budget|received|expenditure|commitments|uncommitted)/i.test(k))return new Intl.NumberFormat("en-GB",{maximumFractionDigits:2}).format(v); if(typeof v==="string"&&/(_at|date|deadline)/.test(k)){const d=new Date(v);if(!isNaN(d.valueOf()))return d.toLocaleDateString("en-GB")} return String(v)}
