"use client";
import {useEffect,useState} from "react";
import {Action,Field,Page,Row,dateText,formValues,human,initialValues,moneyText,payload} from "./client";
import {useLoad,useResource,useWorkbench} from "./context";
import {Badge,DecisionDialog,Empty,ErrorBox,FieldInput,FormDialog,Heading,Link,Loading,Notice,Panel,Stat,Table,field} from "./controls";

const stages=[{label:"Intake and eligibility",values:["DISCOVERED","ELIGIBILITY_REVIEW","DIRECTOR_DECISION","READY_FOR_ASSIGNMENT"]},{label:"Assigned and preparing",values:["ASSIGNED","ACCEPTED","PREPARATION"]},{label:"Review and authorisation",values:["INTERNAL_REVIEW","INSTITUTIONAL_APPROVAL","APPROVED_FOR_SUBMISSION"]},{label:"Submitted and outcome",values:["SUBMITTED","OUTCOME_RECORDED","AWARDED","CLOSED"]}];
const defaultTab:Record<string,string>={"Eligibility & Fit":"Eligibility","Proposal Workspace":"Proposal","Budget Builder":"Budget","Internal Review":"Reviews","Approvals":"Reviews","Submissions":"Submission"};
const descriptions:Record<string,string>={"Applications":"Track institutional applications from discovery through preparation, review, submission and outcome.","Eligibility & Fit":"Assess the funder's conditions before committing proposal effort or assigning a researcher.","Proposal Workspace":"Prepare the required SOI, EOI, LOI, concept note, proposal or fellowship sections with a saved revision history.","Budget Builder":"Build balanced scenarios with separate funder, NHRC and partner contributions.","Internal Review":"Independent scientific, finance, grants and governance reviews for the current proposal revision.","Approvals":"Authorise a reviewed package without confusing institutional approval with a funder's decision.","Submissions":"Record an authorised external submission, its evidence and the funder's subsequent decision."};

export default function ApplicationWorkspace({name,id}:{name:string;id?:string}){
  const {client,go,notify}=useWorkbench(),resource=useResource("applications"),[creating,setCreating]=useState(false),[query,setQuery]=useState(""),[page,setPage]=useState(0);
  const list=useLoad<Page>(!id&&resource?`/records/applications?q=${encodeURIComponent(query)}&page=${page}&size=40`:null);
  if(id)return <ApplicationDetail id={id} initialTab={defaultTab[name]||"Overview"}/>;
  return <><Heading title={name} description={descriptions[name]||descriptions.Applications}>{resource?.canCreate&&<button className="btn primary" onClick={()=>setCreating(true)}>Start application</button>}<button className="btn" onClick={()=>go("Opportunity Intelligence")}>Review funding calls</button></Heading>
    {!resource?<Notice warning>Your current role cannot open applications.</Notice>:<><div className="filters"><div className="field"><label htmlFor="application-search">Find an application</label><input id="application-search" type="search" maxLength={200} value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Search application title or recorded challenge"/></div><button className="btn" onClick={list.reload} disabled={list.loading}>Refresh</button></div>
      {list.error&&<ErrorBox message={list.error} retry={list.reload}/ >}{list.loading?<Loading/>:list.data&&<><p className="subtle">{list.data.total} matching applications. Stage counts below cover the {list.data.items.length} applications on this page.</p><div className="flow">{stages.map(stage=>{const rows=list.data!.items.filter(row=>stage.values.includes(row.stage));return <section className="flowbox" key={stage.label}><h2>{stage.label}</h2><div className="flowcount">{rows.length}</div>{rows.map(row=><div className="item" key={row.id}><h3>{row.title}</h3><span className="tiny">{row.reference} · {human(row.application_type)}</span><Badge value={row.stage}/><p className="tiny">Deadline: {dateText(row.deadline_at)}<br/>{row.current_challenge||"No challenge recorded"}</p><button className="btn small" onClick={()=>go(name,row.id)}>Open application</button></div>)}{!rows.length&&<Empty>No applications at this stage on this page.</Empty>}</section>;})}</div><div className="actions pagination"><button className="btn" disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous page</button><span>Page {page+1}</span><button className="btn" disabled={!list.data.hasMore} onClick={()=>setPage(value=>value+1)}>Next page</button></div></>}
      {creating&&<FormDialog title="Start institutional application" fields={resource.fields} onClose={()=>setCreating(false)} onSave={async values=>{const result=await client<Row>("/records/applications",{method:"POST",body:payload(values)});notify("Application created. Begin the eligibility assessment before assignment.");go("Eligibility & Fit",result.id);}}/>}
    </>}
  </>;
}

function decisionFields(action:Action,row:Row,actorId:string):{fields:Field[];transform:(values:Row)=>Row}{
  const code=action.code;let fields:Field[]=[];
  const choice=(name:string,label:string,choices:string[])=>field(name,label,"select",true,choices);
  const lookup=(name:string,label:string)=>field(name,label,"lookup",true,[],"users");
  if(code==="RECORD_ELIGIBILITY")fields=[choice("decision","Eligibility decision",["ELIGIBLE","CONDITIONAL","INELIGIBLE"]),...Object.entries({applicant:"Applicant and institutional eligibility",geography:"Geographical eligibility",theme:"Research theme and scope",deadline:"Deadline and time available",budget:"Budget and funding limits",partners:"Partner and consortium requirements"}).map(([key,label])=>choice(`check_${key}`,label,["PASS","FAIL","UNKNOWN","NOT_APPLICABLE"])),field("conditions","Outstanding conditions and how they will be resolved","textarea",false)];
  if(code==="DIRECTOR_DECISION")fields=[choice("decision","Institutional decision",["PURSUE","DO_NOT_PURSUE"])];
  if(code==="ASSIGN")fields=[lookup("researcherId","Lead researcher with an active profile")];
  if(code==="REQUEST_REVIEW")fields=[...(["SCIENTIFIC","FINANCE","GRANTS",...(row.narrative?.governanceReviewRequired?["GOVERNANCE"]:[])]).map(type=>lookup(`reviewer_${type}`,`${human(type)} reviewer`)),field("documentsConfirmed","I confirm the package meets the funder's document requirements","boolean")];
  if(code==="COMPLETE_REVIEW")fields=[choice("reviewType","Assigned review",(row.reviews||[]).filter((review:Row)=>review.reviewer_id===actorId&&review.status==="PENDING"&&review.content_revision===row.content_revision).map((review:Row)=>review.review_type)),choice("decision","Review disposition",["CLEARED","RETURNED"]),field("noConflict","I confirm that I have no conflict of interest","boolean")];
  if(code==="APPROVE")fields=[field("noConflict","I confirm that I have no conflict of interest","boolean")];
  if(code==="RECORD_SUBMISSION")fields=[field("submittedAt","Actual submission date, time and time zone","datetime"),field("reference","Funder submission reference")];
  if(code==="RECORD_OUTCOME")fields=[choice("outcome","Recorded funder outcome",[...( ["FULL_PROPOSAL","FELLOWSHIP"].includes(row.application_type)?["AWARDED"]:[]),"UNSUCCESSFUL","WITHDRAWN","INVITED_TO_NEXT_STAGE","WAITLISTED"])];
  if(code==="NEXT_STAGE")fields=[choice("applicationType","Invited submission type",["EOI","CONCEPT_NOTE","FULL_PROPOSAL","FELLOWSHIP"].filter(type=>type!==row.application_type))];
  if(code==="CONVERT_AWARD")fields=[field("reference","Award reference"),field("startDate","Award start date","date"),field("endDate","Award end date","date"),choice("currency","Award currency",["GHS","USD","GBP","EUR","CAD","AUD","CHF","ZAR","KES"]),field("totalAward","Total award","money"),field("nhrcAllocation","NHRC allocation","money"),field("partnerAllocation","Partner allocation","money")];
  return {fields,transform:(values:Row)=>{
    if(code==="RECORD_ELIGIBILITY"){const {decision,conditions,...checks}=values;return {decision,conditions,checks:Object.fromEntries(Object.entries(checks).map(([key,value])=>[key.replace("check_",""),value]))};}
    if(code==="REQUEST_REVIEW"){const {documentsConfirmed,...reviewers}=values;return {documentsConfirmed,reviewers:Object.fromEntries(Object.entries(reviewers).map(([key,value])=>[key.replace("reviewer_",""),value]))};}
    return values;
  }};
}

function ApplicationDetail({id,initialTab}:{id:string;initialTab:string}){
  const {client,actor,go,notify}=useWorkbench(),load=useLoad<Row>(`/applications/${id}`);
  const [tab,setTab]=useState(initialTab),[action,setAction]=useState<Action|null>(null),[budgetLine,setBudgetLine]=useState<Row|null>(null),[documentForm,setDocumentForm]=useState(false),[selectScenario,setSelectScenario]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[dirty,setDirty]=useState(false);
  useEffect(()=>{setTab(initialTab);setDirty(false);setAction(null);},[id,initialTab]);
  const changeTab=(next:string)=>{if(dirty&&!window.confirm("Discard unsaved proposal changes?"))return;setDirty(false);setTab(next);};
  if(load.loading)return <Loading/>;
  if(load.error)return <ErrorBox message={load.error} retry={load.reload}/>;
  const row=load.data;if(!row)return null;
  const available:Action[]=row._actions||[],actions=action?decisionFields(action,row,actor.id):null;
  const mutate=async(operation:()=>Promise<unknown>,message:string)=>{if(busy)return;setBusy(true);setError("");try{await operation();notify(message);load.reload();}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}};
  const refreshed=(result:Row)=>{setDirty(false);if(result.createdApplicationId)go("Eligibility & Fit",result.createdApplicationId);else if(result.createdAwardId)go("Award Setup",result.createdAwardId);else load.reload();};
  return <><Heading title={row.title} description={`${row.reference} · ${human(row.application_type)} · Content revision ${row.content_revision}`}><button className="btn" onClick={()=>go("Applications")}>Application register</button><button className="btn" disabled={busy||dirty} onClick={load.reload}>Refresh</button></Heading>
    <div className="stats"><Stat label="Current stage" value={<Badge value={row.stage}/>} note="Controlled application workflow"/><Stat label="Required narrative sections" value={`${row._readiness}%`} note="Completeness is not a quality score"/><Stat label="Selected budget" value={row.budget_scenario||"Not selected"} note="Scenario used for review and authorisation"/><Stat label="Published deadline" value={dateText(row.deadline_at)} note="Confirm the precise deadline with the funder"/></div>
    <Panel title="Available actions" note="Only decisions available to your identity at the current stage are shown."><div className="panelbody actions">{available.map(item=><button key={item.code} className="btn" disabled={busy||dirty} onClick={()=>setAction(item)}>{item.label}</button>)}{!available.length&&<span className="subtle">There is no decision awaiting this account at the current stage.</span>}{dirty&&<span className="subtle">Save or discard your proposal changes before taking a workflow action.</span>}</div></Panel>
    <div className="tabs workspace-tabs">{["Overview","Eligibility","Proposal","Budget","Documents","Reviews","Submission","History"].map(name=><button className={`tab ${name===tab?"active":""}`} key={name} onClick={()=>changeTab(name)}>{name}</button>)}</div>{error&&<ErrorBox message={error}/>}
    {tab==="Overview"&&<div className="grid"><Panel title="Application progress"><div className="panelbody checks">{stages.map(stage=><p key={stage.label}><strong>{stage.label}</strong>{stage.values.includes(row.stage)?<Badge value={row.stage}/>:"Use the recorded history to inspect earlier decisions."}</p>)}</div></Panel><Panel title="Responsibilities and preparation"><div className="panelbody"><h3>Assignments</h3><Table rows={row.assignments||[]} columns={[{key:"researcher",label:"Researcher"},{key:"response",label:"Response",render:item=><Badge value={item.response}/>},{key:"assigned_at",label:"Assigned",render:item=>dateText(item.assigned_at)}]}/><Notice>{row.current_challenge||"No preparation challenge has been recorded."}</Notice></div></Panel></div>}
    {tab==="Eligibility"&&<><Notice>Use the funding call's original conditions as evidence. Unknown or failed requirements must not be recorded as fully eligible. Conditional cases remain in eligibility review.</Notice><Panel title="Eligibility and pursuit decisions"><Table rows={(row.decisions||[]).filter((item:Row)=>["START_ELIGIBILITY","RECORD_ELIGIBILITY","DIRECTOR_DECISION"].includes(item.gate))} columns={[{key:"gate",label:"Decision stage"},{key:"decision",label:"Decision",render:item=><Badge value={item.decision}/>},{key:"note",label:"Rationale"},{key:"decided_by_name",label:"Decision maker"},{key:"evidence_url",label:"Evidence",render:item=><Link url={item.evidence_url}/>}]/></Panel></>}
    {tab==="Proposal"&&<NarrativeEditor key={`${row.id}-${row.record_version}`} row={row} onSaved={()=>{setDirty(false);load.reload();}} onDirty={setDirty}/>}
    {tab==="Budget"&&<><Panel title="Budget scenarios" note="Amounts are kept separate by scenario and currency. Contributions must balance each line." actions={row._canEditNarrative?<><button className="btn small" onClick={()=>setBudgetLine({scenario:row.budget_scenario||"Base"})}>Add budget line</button><button className="btn small" disabled={!row.budgetLines?.length} onClick={()=>setSelectScenario(true)}>Select review scenario</button></>:undefined}><Table rows={row.budgetTotals||[]} columns={[{key:"scenario",label:"Scenario"},{key:"currency",label:"Currency"},{key:"line_total",label:"Total cost",render:item=>moneyText(item.line_total,item.currency)},{key:"funder_amount",label:"Funder",render:item=>moneyText(item.funder_amount,item.currency)},{key:"nhrc_contribution",label:"NHRC",render:item=>moneyText(item.nhrc_contribution,item.currency)},{key:"partner_amount",label:"Partners",render:item=>moneyText(item.partner_amount,item.currency)},{key:"invalid_lines",label:"Unbalanced lines"}]}/></Panel><Panel title="Detailed costing"><Table rows={row.budgetLines||[]} columns={[{key:"scenario",label:"Scenario"},{key:"category",label:"Category"},{key:"description",label:"Description"},{key:"year_no",label:"Year"},{key:"quantity",label:"Quantity"},{key:"unit_cost",label:"Unit cost",render:item=>moneyText(item.unit_cost,item.currency)},{key:"controls",label:"Actions",render:item=>row._canEditNarrative?<div className="actions"><button className="btn small" disabled={busy} onClick={()=>setBudgetLine(item)}>Edit line</button><button className="btn small danger" disabled={busy} onClick={()=>{if(window.confirm("Remove this draft budget line? Its previous value remains in the decision history."))void mutate(()=>client(`/applications/${id}/budget/${item.id}?version=${row.record_version}`,{method:"DELETE"}),"Draft budget line removed.");}}>Remove line</button></div>:"Locked for review"}]}/></Panel></>}
    {tab==="Documents"&&<Panel title="Controlled document versions" note="Links refer to institutionally controlled files. This is not an unrestricted public file upload." actions={row._canEditNarrative?<button className="btn small" onClick={()=>setDocumentForm(true)}>Add document version</button>:undefined}><Table rows={row.documents||[]} columns={[{key:"document_type",label:"Document type"},{key:"title",label:"Title"},{key:"version_no",label:"Version"},{key:"added_by_name",label:"Recorded by"},{key:"evidence_url",label:"Document",render:item=><Link url={item.evidence_url} children="Open document"/>}]}/></Panel>}
    {tab==="Reviews"&&<><Notice>Reviews apply to the current content revision. Returned proposals must be corrected and reviewed again before institutional authorisation.</Notice><Panel title="Assigned reviews"><Table rows={row.reviews||[]} columns={[{key:"review_type",label:"Review"},{key:"reviewer",label:"Assigned reviewer"},{key:"content_revision",label:"Revision"},{key:"status",label:"Disposition",render:item=><Badge value={item.status}/>},{key:"comments",label:"Comments"}]}/></Panel><Panel title="Institutional decisions"><Table rows={(row.decisions||[]).filter((item:Row)=>["COMPLETE_REVIEW","APPROVE","RETURN"].includes(item.gate))} columns={[{key:"gate",label:"Action"},{key:"decision",label:"Decision"},{key:"content_revision",label:"Revision"},{key:"decided_by_name",label:"Authorised officer"},{key:"note",label:"Decision note"}]}/></Panel></>}
    {tab==="Submission"&&<div className="grid"><Panel title="External submission record"><div className="panelbody"><dl className="kv"><dt>Reference</dt><dd>{human(row.submission_reference)}</dd><dt>Submitted</dt><dd>{dateText(row.submitted_at)}</dd><dt>Evidence</dt><dd><Link url={row.submission_evidence_url}/></dd><dt>Funder outcome</dt><dd><Badge value={row.funder_outcome}/></dd><dt>Outcome evidence</dt><dd><Link url={row.outcome_evidence_url}/></dd></dl></div></Panel><Panel title="Submission safeguards"><div className="panelbody checks"><p><strong>Institutional authorisation first</strong>The current package must be authorised before submission can be recorded.</p><p><strong>No automatic funder submission</strong>Staff submit through the funder's approved channel, then record the reference and evidence here.</p><p><strong>Early-stage applications</strong>An SOI, EOI, LOI or concept note advances through a linked invitation. It is not recorded as a financial award.</p></div></Panel></div>}
    {tab==="History"&&<Panel title="Recorded stage history"><Table rows={row.history||[]} columns={[{key:"from_stage",label:"Previous stage"},{key:"to_stage",label:"New stage"},{key:"changed_by_name",label:"Recorded by"},{key:"changed_at",label:"Date",render:item=>dateText(item.changed_at)},{key:"note",label:"Decision note"}]}/></Panel>}
    {action&&actions&&<DecisionDialog action={action} record={row} route={`/applications/${id}/actions`} fields={actions.fields} transform={actions.transform} onClose={()=>setAction(null)} onDone={refreshed}/>}
    {budgetLine&&<FormDialog title={budgetLine.id?"Edit budget line":"Add budget line"} fields={row.budgetFields} record={budgetLine} note="Quantity × unit cost must equal the funder, NHRC and partner contributions combined. Money is checked using exact decimal calculations by the service." onClose={()=>setBudgetLine(null)} onSave={async values=>{await client(`/applications/${id}/budget${budgetLine.id?`/${budgetLine.id}`:""}`,{method:budgetLine.id?"PUT":"POST",body:payload(values,row.record_version)});notify("Budget line saved and balanced.");load.reload();}}/>}
    {selectScenario&&<FormDialog title="Select the scenario for review" fields={[field("scenario","Budget scenario","select",true,Array.from(new Set<string>((row.budgetLines||[]).map((item:Row)=>item.scenario))))]} record={{scenario:row.budget_scenario}} onClose={()=>setSelectScenario(false)} onSave={async values=>{await client(`/applications/${id}/budget-scenario`,{method:"PUT",body:payload(values,row.record_version)});notify("Review scenario selected.");load.reload();}}/>}
    {documentForm&&<FormDialog title="Add controlled document version" fields={[field("document_type","Document type"),field("title","Document title"),field("evidence_url","Institutionally controlled document link","url")]} onClose={()=>setDocumentForm(false)} onSave={async values=>{await client(`/applications/${id}/documents`,{method:"POST",body:payload(values,row.record_version)});notify("Document version recorded.");load.reload();}}/>}
  </>;
}

function NarrativeEditor({row,onSaved,onDirty}:{row:Row;onSaved:()=>void;onDirty:(value:boolean)=>void}){
  const {client,notify}=useWorkbench();
  const fields:Field[]=(row.narrativeFields||[]).map((item:Field)=>({...item,required:false}));
  const [values,setValues]=useState<Row>(()=>initialValues(fields,row.narrative||{})),[busy,setBusy]=useState(false),[error,setError]=useState(""),[dirty,setDirty]=useState(false);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  return <Panel title={`${human(row.application_type)} preparation`} note="Incomplete drafts can be saved. All required sections must be completed before internal review."><div className="panelbody"><Notice>Required for this submission type: {(row._requiredSections||[]).map((name:string)=>fields.find(item=>item.name===name)?.label||name).join("; ")}.</Notice><form data-unsaved={dirty?"true":"false"} onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError("");try{await client(`/applications/${row.id}/narrative`,{method:"PUT",body:payload(formValues(fields,values),row.record_version)});setDirty(false);onDirty(false);notify("Proposal draft saved as a new content revision.");onSaved();}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}}}>{error&&<ErrorBox message={error}/>}<div className="formgrid">{fields.map(item=><FieldInput key={item.name} field={item} value={values[item.name]} disabled={busy||!row._canEditNarrative} onChange={value=>{setValues(current=>({...current,[item.name]:value}));setDirty(true);onDirty(true);}}/>)}</div>{row._canEditNarrative?<div className="actions"><button className="btn primary" type="submit" disabled={busy||!dirty}>{busy?"Saving draft...":"Save proposal draft"}</button><button className="btn" type="button" disabled={busy||!dirty} onClick={()=>{if(window.confirm("Discard unsaved proposal changes?")){setValues(initialValues(fields,row.narrative||{}));setDirty(false);onDirty(false);}}}>Discard changes</button></div>:<Notice>This revision is read-only at the current stage or for your assigned role.</Notice>}</form></div></Panel>;
}
