"use client";
import {useState} from "react";
import {Action,Row,dateText,human,moneyText} from "./client";
import {useLoad,useWorkbench} from "./context";
import {Badge,DecisionDialog,ErrorBox,Heading,Link,Loading,Notice,Panel,Stat,Table,field} from "./controls";

export default function AwardWorkspace({name,id}:{name:string;id?:string}){
  const {go}=useWorkbench();const [query,setQuery]=useState("");
  const list=useLoad<Row>(id?null:`/awards?q=${encodeURIComponent(query)}`);
  if(id)return <AwardDetail id={id}/>;
  return <><Heading title={name} description="Maintain the approved award, accountable research lead, institutional obligations and documented closeout."><button className="btn" onClick={()=>go("Submissions")}>Review application outcomes</button><button className="btn" disabled={list.loading} onClick={list.reload}>Refresh</button></Heading><Notice>Award records are created from a recorded financial award outcome. They are not created by treating an SOI or EOI invitation as funding received.</Notice><div className="filters"><div className="field"><label htmlFor="award-search">Search awards</label><input id="award-search" type="search" maxLength={200} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Award title or reference"/></div></div>{list.error?<ErrorBox message={list.error} retry={list.reload}/>:list.loading?<Loading/>:<Panel title="Institutional award register" note="Values are displayed in each award's approved currency."><Table rows={list.data?.items||[]} columns={[{key:"title",label:"Award / research lead",render:row=><><b>{row.title}</b><span className="tiny">{row.reference} · {human(row.principal_investigator)}</span></>},{key:"funder",label:"Funder"},{key:"nhrc_allocation",label:"NHRC allocation",render:row=>moneyText(row.nhrc_allocation,row.currency)},{key:"end_date",label:"End date",render:row=>dateText(row.end_date)},{key:"status",label:"Stage",render:row=><Badge value={row.status}/>}]} onOpen={row=>go(name,row.id)}/></Panel>}{list.data?.truncated&&<Notice warning>The register displays its first 200 matching awards. Refine the search to retrieve the remaining records.</Notice>}</>;
}

function AwardDetail({id}:{id:string}){
  const {go}=useWorkbench(),load=useLoad<Row>(`/awards/${id}`);
  const [tab,setTab]=useState("Setup"),[action,setAction]=useState<Action|null>(null);
  if(load.loading)return <Loading/>;
  if(load.error)return <ErrorBox message={load.error} retry={load.reload}/>;
  const row=load.data;if(!row)return null;
  const checklistNames={agreement:"Agreement and approved terms",finance:"Finance setup and approved allocation",reporting:"Reporting and delivery requirements",governance:"Ethics, regulatory and information requirements",partners:"Partner and subaward requirements"};
  const fields=action?.code==="ACTIVATE"?[field("noConflict","I have no conflict of interest in this authorisation","boolean"),...Object.entries(checklistNames).map(([name,label])=>field(`setup_${name}`,label,"select",true,["CONFIRMED","NOT_APPLICABLE"]))]:action?.code==="CLOSE_AWARD"?[field("noConflict","I have no conflict of interest in this authorisation","boolean")]:[];
  const decisionTransform=(values:Row)=>action?.code==="ACTIVATE"?{noConflict:values.noConflict,setupChecks:Object.fromEntries(Object.entries(values).filter(([key])=>key.startsWith("setup_")).map(([key,value])=>[key.slice(6),value]))}:values;
  return <><Heading title={row.title} description={`${row.reference} · Institutional award management`}><button className="btn" onClick={()=>go("Award Register")}>Award register</button><button className="btn" onClick={load.reload}>Refresh</button></Heading><div className="stats"><Stat label="Award stage" value={<Badge value={row.status}/>}/><Stat label="NHRC allocation" value={moneyText(row.nhrc_allocation,row.currency)} note="Not a statement of cash received"/><Stat label="Start date" value={dateText(row.start_date)}/><Stat label="End date" value={dateText(row.end_date)}/></div>
    <Panel title="Authorised award actions" note="Activation and final closeout require independent institutional authority."><div className="panelbody actions">{(row._actions||[]).map((item:Action)=><button key={item.code} className="btn primary" onClick={()=>setAction(item)}>{item.label}</button>)}{!row._actions?.length&&<span className="subtle">There is no award decision available for your role at this stage.</span>}</div></Panel>
    <div className="tabs workspace-tabs">{["Setup","Agreements","Partners","Governance","Deliverables","Closeout","History"].map(name=><button className={`tab ${tab===name?"active":""}`} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div>
    {tab==="Setup"&&<div className="grid"><Panel title="Setup readiness" note="Recorded evidence supports the director's activation decision."><div className="panelbody checks"><p><strong>Agreement</strong>{row.contracts?.some((item:Row)=>item.status==="APPROVED"&&item.storage_key)?"An approved agreement with a controlled link is recorded.":"An approved agreement and controlled document link are required."}</p><p><strong>Reporting and delivery</strong>{row.deliverables?.length||0} obligations recorded.</p><p><strong>Partners</strong>{row.partners?.filter((item:Row)=>item.agreement_status!=="ACTIVE").length||0} partner agreements awaiting completion.</p><p><strong>Governance</strong>Review external approvals and expiry dates before authorising work.</p></div></Panel><Panel title="Award workspaces"><div className="panelbody actions">{["Contracts & Agreements","Partners & Subawards","Due Diligence","Deliverables","Ethics & Regulatory Links","Finance Dashboard","Procurement Plans","Risks & Issues"].map(name=><button className="btn" key={name} onClick={()=>go(name)}>{name}</button>)}</div></Panel></div>}
    {tab==="Agreements"&&<Panel title="Award agreements" actions={<button className="btn small" onClick={()=>go("Contracts & Agreements")}>Manage agreements</button>}><Table rows={row.contracts||[]} columns={[{key:"title",label:"Agreement"},{key:"reference",label:"Reference"},{key:"status",label:"Approval",render:item=><Badge value={item.status}/>},{key:"expiry_date",label:"Expiry",render:item=>dateText(item.expiry_date)},{key:"storage_key",label:"Evidence",render:item=><Link url={item.storage_key}/>} ]}/></Panel>}
    {tab==="Partners"&&<Panel title="Partners and subawards" actions={<button className="btn small" onClick={()=>go("Partners & Subawards")}>Manage partners</button>}><Table rows={row.partners||[]} columns={[{key:"partner_name",label:"Partner"},{key:"role",label:"Contribution"},{key:"due_diligence_status",label:"Due diligence",render:item=><Badge value={item.due_diligence_status}/>},{key:"agreement_status",label:"Agreement",render:item=><Badge value={item.agreement_status}/>} ]}/></Panel>}
    {tab==="Governance"&&<Panel title="Recorded external approvals" actions={<button className="btn small" onClick={()=>go("Ethics & Regulatory Links")}>Manage approvals</button>}><Table rows={row.compliance||[]} columns={[{key:"compliance_type",label:"Requirement"},{key:"authority",label:"Authority"},{key:"reference",label:"Reference"},{key:"expiry_date",label:"Expiry",render:item=>dateText(item.expiry_date)},{key:"status",label:"Status",render:item=><Badge value={item.status}/>} ]}/></Panel>}
    {tab==="Deliverables"&&<Panel title="Delivery obligations" actions={<button className="btn small" onClick={()=>go("Deliverables")}>Manage deliverables</button>}><Table rows={row.deliverables||[]} columns={[{key:"title",label:"Deliverable"},{key:"due_date",label:"Due date",render:item=>dateText(item.due_date)},{key:"status",label:"Progress",render:item=><Badge value={item.status}/>} ]}/></Panel>}
    {tab==="Closeout"&&<><Notice>Final closeout checks technical reports, finance, partner accountability, assets, information retention and compliance. Outstanding financial records block closure.</Notice><Panel title="Controlled closeout checklist" actions={<button className="btn small" onClick={()=>go("Closeout")}>Manage closeout evidence</button>}><Table rows={row.closeout||[]} columns={[{key:"item_type",label:"Area"},{key:"title",label:"Requirement"},{key:"status",label:"Completion",render:item=><Badge value={item.status}/>},{key:"evidence_storage_key",label:"Evidence",render:item=><Link url={item.evidence_storage_key}/>} ]}/></Panel></>}
    {tab==="History"&&<Panel title="Award decision history"><Table rows={row.history||[]} columns={[{key:"action",label:"Action"},{key:"actor",label:"Recorded by"},{key:"occurred_at",label:"Date",render:item=>dateText(item.occurred_at)},{key:"note",label:"Decision note"}]}/></Panel>}
    {action&&<DecisionDialog action={action} record={row} route={`/awards/${id}/actions`} fields={fields} transform={decisionTransform} onClose={()=>setAction(null)} onDone={load.reload}/>}
  </>;
}
