"use client";
import {useState,type ReactNode} from "react";
import {Action,Field,Page,Row,dateText,human,moneyText,payload} from "./client";
import {useLoad,useResource,useWorkbench} from "./context";
import {Badge,DecisionDialog,Details,Empty,ErrorBox,FormDialog,Heading,Loading,Modal,Notice,Panel,Stat,Table} from "./controls";

export type RegisterOptions={resourceKey:string;title:string;description:string;createLabel:string;layout?:"table"|"cards"|"calendar";columns?:string[];filter?:(row:Row)=>boolean;notice?:string;children?:ReactNode;extra?:(row:Row,reload:()=>void)=>ReactNode;selectedId?:string;onOpen?:(row:Row)=>void};
export default function RecordWorkspace(props:RegisterOptions){
  const {client,notify,actor}=useWorkbench(),resource=useResource(props.resourceKey);
  const [search,setSearch]=useState(""),[page,setPage]=useState(0),[selected,setSelected]=useState<string|null>(props.selectedId||null),[creating,setCreating]=useState(false);
  const list=useLoad<Page>(resource?`/records/${props.resourceKey}?q=${encodeURIComponent(search)}&page=${page}&size=30`:null);
  if(!resource)return <><Heading title={props.title} description={props.description}/><Notice warning>Your current role does not have access to this register. Choose an authorised account or request access through the institutional process.</Notice></>;
  const rows=(list.data?.items||[]).filter(props.filter||(()=>true));
  const open=(row:Row)=>props.onOpen?props.onOpen(row):setSelected(row.id);
  const names=props.columns||resource.fields.filter(field=>["text","select","date","money","tags","email"].includes(field.kind)).slice(0,5).map(field=>field.name);
  const columns=names.map(name=>{const f=resource.fields.find(field=>field.name===name);return {key:name,label:f?.label||human(name),render:(row:Row)=>f?.kind==="date"?dateText(row[name]):f?.kind==="money"?moneyText(row[name],row.currency):human(row[name])};});
  if(resource.statusColumn)columns.push({key:resource.statusColumn,label:"Status",render:(row:Row)=><Badge value={row[resource.statusColumn!]}/>});
  return <><Heading title={props.title} description={props.description}>{resource.canCreate&&<button className="btn primary" onClick={()=>setCreating(true)}>{props.createLabel}</button>}<button className="btn" onClick={list.reload} disabled={list.loading}>Refresh</button></Heading>{props.notice&&<Notice>{props.notice}</Notice>}{props.children}
    <div className="filters"><div className="field"><label htmlFor={`search-${props.resourceKey}`}>Search this register</label><input id={`search-${props.resourceKey}`} type="search" value={search} maxLength={200} placeholder="Search recorded information" onChange={event=>{setSearch(event.target.value);setPage(0);}}/></div><span className="subtle">{list.data?`${list.data.total} matching records; page ${page+1}`:""}</span></div>
    {list.error&&<ErrorBox message={list.error} retry={list.reload}/ >}{list.loading?<Loading/>:list.data&&<>
      {props.filter&&<p className="subtle">Showing {rows.length} matching items from this page of the shared register.</p>}
      {props.layout==="cards"?<div className="profilegrid">{rows.map(row=><section className="panel profilecard" key={row.id}><div className="panelhead"><div><h2>{human(row.legal_name||row.name||row.title||row.summary||"Researcher profile")}</h2><p>{human(row.organisation_type||row.career_stage||row.short_name)}</p></div>{resource.statusColumn&&<Badge value={row[resource.statusColumn]}/>}</div><div className="panelbody"><div className="taglist">{(row.expertise||row.research_themes||[]).slice(0,8).map((term:string)=><span key={term} className="badge good">{term}</span>)}</div><p className="subtle">{String(row.summary||row.capabilities||row.funding_interests||row.facilities||"").slice(0,220)}</p><p className="tiny">Required profile fields: {row._requiredComplete} of {row._requiredTotal} recorded</p><button className="btn small" onClick={()=>open(row)}>Open profile</button></div></section>)}{!rows.length&&<Empty>No profiles match this search. Authorised staff can add a profile using the form above.</Empty>}</div>:
      props.layout==="calendar"?<Panel title="Scheduled obligations" note="Ordered by the dates recorded in this register."><div className="panelbody">{[...rows].sort((a,b)=>String(a.scheduled_date||a.due_date||a.expiry_date||"").localeCompare(String(b.scheduled_date||b.due_date||b.expiry_date||""))).map(row=><div className="item" key={row.id}><div><h3>{human(row.title||row.maintenance_type||row.service_type||row.requirement||row.compliance_type)}</h3><span className="tiny">{dateText(row.scheduled_date||row.due_date||row.expiry_date)}</span></div><div className="actions"><Badge value={row.status}/><button className="btn small" onClick={()=>open(row)}>Open obligation</button></div></div>)}{!rows.length&&<Empty>No dated obligations on this page.</Empty>}</div></Panel>:<Panel title={resource.title} note="Open a record to inspect the complete form, permitted actions and decision history."><Table rows={rows} columns={columns} onOpen={open}/></Panel>}
      <div className="actions pagination"><button className="btn small" disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous page</button><span>Page {page+1}</span><button className="btn small" disabled={!list.data.hasMore} onClick={()=>setPage(value=>value+1)}>Next page</button></div></>}
    {creating&&<FormDialog title={props.createLabel} fields={resource.fields} record={props.resourceKey==="researchers"?{user_id:actor.id}:undefined} onClose={()=>setCreating(false)} onSave={async values=>{const result=await client<Row>(`/records/${props.resourceKey}`,{method:"POST",body:payload(values)});notify("Record saved successfully.");list.reload();open(result);}}/>}
    {selected&&<RecordDetail resourceKey={props.resourceKey} id={selected} onClose={()=>setSelected(null)} onChanged={list.reload} extra={props.extra}/>}
  </>;
}

export function RecordDetail({resourceKey,id,onClose,onChanged,extra}:{resourceKey:string;id:string;onClose:()=>void;onChanged:()=>void;extra?:(row:Row,reload:()=>void)=>ReactNode}){
  const {client,notify}=useWorkbench(),resource=useResource(resourceKey),record=useLoad<Row>(`/records/${resourceKey}/${id}`),history=useLoad<Row[]>(`/records/${resourceKey}/${id}/history`);
  const [editing,setEditing]=useState(false),[action,setAction]=useState<Action|null>(null),[tab,setTab]=useState("Record");
  const refresh=()=>{record.reload();history.reload();onChanged();};
  if(!resource)return null;
  const row=record.data;
  return <>{!editing&&!action&&<Modal title={row?human(row.title||row.legal_name||row.name||resource.title):resource.title} onClose={onClose} wide><div className="tabs">{["Record","History",...(extra?["Related information"]:[])].map(name=><button type="button" className={`tab ${name===tab?"active":""}`} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div>{record.loading?<Loading/>:record.error?<ErrorBox message={record.error} retry={record.reload}/>:row&&<><div className="actions recordactions">{resource.statusColumn&&<Badge value={row[resource.statusColumn]}/ >}{row._editable&&<button className="btn primary" onClick={()=>setEditing(true)}>Edit record</button>}{(row._actions||[]).map((item:Action)=><button key={item.code} className="btn" onClick={()=>setAction(item)}>{item.label}</button>)}</div>{tab==="Record"&&<Details fields={resource.fields} record={row}/ >}{tab==="History"&&(history.loading?<Loading/>:history.error?<ErrorBox message={history.error} retry={history.reload}/>:<Table rows={history.data||[]} columns={[{key:"action",label:"Action"},{key:"actor",label:"Recorded by"},{key:"occurred_at",label:"Date",render:item=>dateText(item.occurred_at)},{key:"note",label:"Decision note"}]}/>)}{tab==="Related information"&&extra?.(row,refresh)}<p className="tiny">Record version {row.record_version}. Only actions permitted for your role and this stage are shown.</p></>}</Modal>}
  {editing&&row&&<FormDialog title={`Edit ${resource.title.toLowerCase()}`} fields={resource.fields} record={row} onClose={()=>setEditing(false)} onSave={async values=>{await client(`/records/${resourceKey}/${id}`,{method:"PATCH",body:payload(values,row.record_version)});notify("Changes saved successfully.");refresh();}}/>}
  {action&&row&&<DecisionDialog action={action} record={row} route={`/records/${resourceKey}/${id}/actions`} onClose={()=>setAction(null)} onDone={refresh}/>}
  </>;
}
