package org.nhrc.grants.workbench

/** Only these server-owned names can become SQL table or column identifiers. */
data class GrantField(val name: String,val label: String,val kind: String="text",val required: Boolean=false,val choices: List<String> = emptyList(),val lookup: String?=null,val defaultValue: String?=null,val maxLength: Int=4000)
data class GrantTransition(val code: String,val label: String,val from: Set<String>,val to: String,val roles: Set<String>,val independent: Boolean=false,val evidenceRequired: Boolean=false)
data class GrantResource(val key: String,val title: String,val table: String,val fields: List<GrantField>,val readers: Set<String>,val writers: Set<String>,val statusColumn: String?="status",val initialStatus: String?=null,val awardColumn: String?=null,val creatorColumn: String?=null,val transitions: List<GrantTransition> = emptyList())

object WorkbenchCatalogue {
    val grantRoles=setOf("GRANTS_OFFICER","POST_AWARD_OFFICER")
    val financeRoles=setOf("FINANCE_OFFICER","FINANCE_APPROVER")
    val procurementRoles=setOf("PROCUREMENT_OFFICER")
    val labRoles=setOf("LABORATORY_OFFICER")
    val governanceRoles=setOf("GOVERNANCE_OFFICER")
    val oversight=setOf("DIRECTOR","AUDITOR")
    val allBusiness=grantRoles+financeRoles+procurementRoles+labRoles+governanceRoles+oversight+setOf("RESEARCHER","ADMIN")
    val profileWriters=setOf("GRANTS_OFFICER","ADMIN")
    val callTypes=listOf("GRANT_CALL","SOI","EOI","LOI","CONCEPT_NOTE","FULL_PROPOSAL","FELLOWSHIP","TENDER")
    val applicationTypes=listOf("SOI","EOI","LOI","CONCEPT_NOTE","FULL_PROPOSAL","FELLOWSHIP")
    val currencies=listOf("GHS","USD","GBP","EUR","CAD","AUD","CHF","ZAR","KES")
    fun text(n:String,l:String,required:Boolean=false,max:Int=255)=GrantField(n,l,required=required,maxLength=max)
    fun area(n:String,l:String,required:Boolean=false)=GrantField(n,l,"textarea",required,maxLength=24000)
    fun select(n:String,l:String,values:List<String>,default:String?=null,required:Boolean=true)=GrantField(n,l,"select",required,values,defaultValue=default)
    fun link(n:String,l:String,lookup:String,required:Boolean=false)=GrantField(n,l,"lookup",required,lookup=lookup)
    fun date(n:String,l:String,required:Boolean=false)=GrantField(n,l,"date",required)
    fun money(n:String,l:String,required:Boolean=true)=GrantField(n,l,"money",required,defaultValue="0")
    fun url(n:String,l:String)=GrantField(n,l,"url",maxLength=2000)
    fun email(n:String,l:String)=GrantField(n,l,"email",maxLength=320)
    fun tags(n:String,l:String)=GrantField(n,l,"tags",maxLength=120)
    val currency=select("currency","Currency",currencies,"GHS")
    val award=link("award_id","Award","awards",true)
    val owner=link("owner_user_id","Responsible officer","users")
    val evidence=url("storage_key","Controlled evidence link")
    fun deliveryFlow(roles:Set<String>)=listOf(
        GrantTransition("START","Start work",setOf("NOT_STARTED","PENDING","RETURNED"),"IN_PROGRESS",roles),
        GrantTransition("RECORD_SUBMISSION","Record submission",setOf("IN_PROGRESS"),"SUBMITTED",roles,evidenceRequired=true),
        GrantTransition("RECORD_ACCEPTANCE","Record external acceptance",setOf("SUBMITTED"),"ACCEPTED",grantRoles,evidenceRequired=true),
        GrantTransition("RETURN","Return for correction",setOf("SUBMITTED"),"RETURNED",grantRoles+oversight,evidenceRequired=true))
    fun reviewFlow(roles:Set<String>,approvers:Set<String>)=listOf(
        GrantTransition("REQUEST_REVIEW","Request review",setOf("DRAFT","RETURNED"),"PENDING",roles),
        GrantTransition("APPROVE","Approve",setOf("PENDING"),"APPROVED",approvers,true,true),
        GrantTransition("RETURN","Return for correction",setOf("PENDING"),"RETURNED",approvers,true))
    private fun r(key:String,title:String,table:String,fields:List<GrantField>,writers:Set<String>,status:String?="status",initial:String?=null,awardColumn:String?=null,creator:String?=null,flow:List<GrantTransition> = emptyList(),readers:Set<String> = writers+oversight+grantRoles):GrantResource {
        val permittedReaders=readers+flow.flatMap { it.roles }
        return GrantResource(key,title,table,fields,permittedReaders,writers,if(key=="applications") "stage" else status,initial,awardColumn,creator,flow)
    }
    val resources:Map<String,GrantResource> = listOf(
        r("institutions","Institutional profiles","institution_profiles",listOf(
            link("organisation_unit_id","Institutional unit","units"),text("legal_name","Legal name",true),text("short_name","Short name"),text("country_code","Country code",max=3),text("organisation_type","Organisation type"),text("registration_reference","Registration reference"),url("website","Website"),text("contact_name","Grants contact"),email("contact_email","Grants contact email"),tags("research_themes","Research themes"),tags("methods","Research methods"),area("facilities","Facilities"),area("research_platforms","Research platforms"),area("strategic_priorities","Strategic priorities"),area("eligibility_notes","Institutional eligibility notes")
        ),profileWriters,status=null,readers=allBusiness),
        r("researchers","Researcher profiles","researcher_profiles",listOf(
            link("user_id","Researcher","users",true),GrantField("orcid","ORCID","orcid",maxLength=19),tags("expertise","Expertise and research themes"),tags("methods","Methods"),select("career_stage","Career stage",listOf("EARLY_CAREER","MID_CAREER","SENIOR","OTHER"),required=false),area("summary","Researcher-approved profile summary"),area("selected_track_record","Selected grants, publications and collaborations"),area("availability_note","Availability for proposal work")
        ),profileWriters+"RESEARCHER",status=null,readers=allBusiness),
        r("partners","Partner directory","partners",listOf(text("name","Institution name",true),text("country_code","Country code",max=3),text("organisation_type","Organisation type"),text("primary_contact_name","Primary contact"),email("primary_contact_email","Contact email").copy(maxLength=255),url("website","Website"),area("capabilities","Capabilities and partnership interests")),profileWriters,status=null,readers=allBusiness),
        r("funders","Funder directory","funders",listOf(text("name","Funder name",true),text("country_code","Country code",max=3),url("website","Website"),email("contact_email","Contact email"),area("funding_interests","Funding interests")),profileWriters,status=null,readers=allBusiness),
        r("opportunities","Opportunity intelligence","opportunities",listOf(text("title","Funding call title",true,max=1000),select("call_type","Call type",callTypes,"GRANT_CALL"),link("funder_id","Funder","funders"),text("source_reference","Funder reference"),url("url","Official call page"),area("summary","Call summary"),area("eligibility_criteria","Eligibility criteria from the call"),tags("keywords","Research themes and keywords"),select("currency","Award currency",currencies,required=false),money("amount_min","Minimum award",false).copy(defaultValue=null),money("amount_max","Maximum award",false).copy(defaultValue=null),date("deadline_date","Published closing date (time not inferred)"),GrantField("deadline_at","Exact deadline with time zone, when stated","datetime")),setOf("GRANTS_OFFICER"),initial="DISCOVERED",creator="created_by",readers=allBusiness),
        r("applications","Applications","applications",listOf(text("title","Application title",true,max=1000),link("opportunity_id","Funding call","opportunities",true),select("application_type","Submission type",applicationTypes,"FULL_PROPOSAL"),area("current_challenge","Current challenges and support required")),setOf("GRANTS_OFFICER"),initial="DISCOVERED",creator="owner_user_id",readers=allBusiness),
        r("contracts","Contracts and agreements","contracts",listOf(award,link("partner_id","Partner","partners"),text("contract_type","Agreement type",true),text("reference","Reference"),text("title","Agreement title",true),date("effective_date","Effective date"),date("expiry_date","Expiry date"),owner,evidence),grantRoles+governanceRoles,initial="DRAFT",awardColumn="award_id",flow=reviewFlow(grantRoles+governanceRoles,setOf("DIRECTOR"))),
        r("award-partners","Partners and subawards","award_partners",listOf(award,link("partner_id","Partner","partners",true),text("role","Partner role"),money("approved_allocation","Proposed allocation"),currency),grantRoles,status="agreement_status",initial="PENDING",awardColumn="award_id",flow=listOf(GrantTransition("RECORD_AGREEMENT","Record signed partner agreement",setOf("PENDING"),"ACTIVE",grantRoles,true,true))),
        r("amendments","Amendment requests","amendments",listOf(award,text("amendment_type","Amendment type",true),text("reference","Reference"),area("justification","Justification",true),GrantField("funder_approval_required","Funder approval required","boolean",defaultValue="true"),date("effective_date","Proposed effective date")),grantRoles,status="internal_status",initial="DRAFT",awardColumn="award_id",creator="requested_by",flow=reviewFlow(grantRoles,setOf("DIRECTOR"))),
        r("deliverables","Deliverables","award_deliverables",listOf(award,text("deliverable_type","Deliverable type",true),text("title","Title",true),date("due_date","Due date",true),owner,url("evidence_storage_key","Evidence link")),grantRoles+"RESEARCHER",initial="NOT_STARTED",awardColumn="award_id",flow=deliveryFlow(grantRoles+"RESEARCHER")),
        r("risks","Risks and issues","award_risks",listOf(award,text("title","Risk or issue",true),area("description","Description"),select("likelihood","Likelihood",listOf("LOW","MEDIUM","HIGH"),"MEDIUM"),select("impact","Impact",listOf("LOW","MEDIUM","HIGH"),"MEDIUM"),owner,area("mitigation","Mitigation and next action"),date("review_date","Review date")),grantRoles+"RESEARCHER",initial="OPEN",awardColumn="award_id",flow=listOf(GrantTransition("CLOSE","Close with evidence",setOf("OPEN"),"CLOSED",grantRoles,true,true),GrantTransition("REOPEN","Reopen",setOf("CLOSED"),"OPEN",grantRoles))),
        r("receipts","Funds received","fund_receipts",listOf(award,GrantField("instalment_no","Instalment number","integer"),money("expected_amount","Expected amount"),date("expected_date","Expected date"),money("received_amount","Received amount",false).copy(defaultValue=null),date("received_date","Received date"),currency,text("reference","Finance reference",true)),financeRoles,status=null,awardColumn="award_id"),
        r("expenditures","Expenditure records","expenditures",listOf(award,date("transaction_date","Transaction date",true),text("category","Cost category",true),area("description","Description"),money("amount","Amount"),currency,text("finance_reference","Source accounting reference",true)),financeRoles,status=null,awardColumn="award_id"),
        r("commitments","Outstanding commitments","commitments",listOf(award,text("category","Cost category",true),area("description","Description"),money("amount","Outstanding amount"),currency,date("expected_date","Expected settlement date")),financeRoles,initial="OPEN",awardColumn="award_id",flow=listOf(GrantTransition("CLOSE","Close commitment",setOf("OPEN"),"CLOSED",financeRoles,true,true))),
        r("advances","Partner advances","partner_advances",listOf(link("award_partner_id","Award partner","award-partners",true),money("amount_advanced","Amount advanced"),money("amount_accounted","Amount accounted for"),currency,date("advanced_date","Advance date",true),date("retirement_due_date","Accountability due date")),financeRoles,initial="OUTSTANDING"),
        r("financial-reports","Financial reporting","financial_reports",listOf(award,date("period_start","Period start"),date("period_end","Period end"),date("due_date","Due date",true),evidence),financeRoles,initial="NOT_STARTED",awardColumn="award_id",creator="prepared_by",flow=deliveryFlow(financeRoles)),
        r("forecasts","Financial forecasts","financial_forecasts",listOf(award,date("forecast_date","Forecast date",true),date("period_end","Forecast period end",true),money("forecast_expenditure","Forecast expenditure"),money("forecast_commitments","Forecast commitments"),currency,area("assumptions","Assumptions",true)),financeRoles,status=null,awardColumn="award_id",creator="prepared_by"),
        r("reconciliations","Reconciliations","reconciliations",listOf(award,date("period_end","Period end",true),money("ledger_amount","Accounting system amount"),money("platform_amount","Grant record amount"),area("note","Reconciliation explanation",true)),financeRoles,initial="OPEN",awardColumn="award_id",flow=listOf(GrantTransition("RECONCILE","Approve reconciliation",setOf("OPEN"),"RECONCILED",setOf("FINANCE_APPROVER"),true,true))),
        r("procurement-plans","Procurement plans","procurement_plans",listOf(award,area("item_description","Item description",true),text("category","Category",true),money("estimated_amount","Estimated amount"),currency,date("planned_date","Planned date"),text("procurement_method","Procurement method",true),owner),procurementRoles,initial="PLANNED",awardColumn="award_id"),
        r("requisitions","Requisitions","procurement_requisitions",listOf(award,link("plan_id","Procurement plan","procurement-plans"),text("reference","Requisition reference",true),area("description","Requirement and justification",true),money("amount","Estimated amount"),currency),procurementRoles,initial="DRAFT",awardColumn="award_id",creator="requested_by",flow=reviewFlow(procurementRoles,setOf("FINANCE_APPROVER"))),
        r("suppliers","Supplier directory","suppliers",listOf(text("name","Supplier name",true),text("country_code","Country code",max=3),email("contact_email","Contact email").copy(maxLength=255)),procurementRoles,status=null),
        r("purchase-orders","Purchase orders","purchase_orders",listOf(link("requisition_id","Approved requisition","requisitions",true),link("supplier_id","Approved supplier","suppliers",true),text("reference","Purchase order reference",true),money("amount","Order amount"),currency,date("issued_date","Issue date"),date("expected_delivery_date","Expected delivery")),procurementRoles,initial="DRAFT",flow=listOf(GrantTransition("ISSUE","Record authorised purchase order",setOf("DRAFT"),"ISSUED",procurementRoles,true,true),GrantTransition("RECEIVE","Record delivery",setOf("ISSUED"),"RECEIVED",procurementRoles,false,true))),
        r("procurement-contracts","Procurement contracts","procurement_contracts",listOf(link("purchase_order_id","Purchase order","purchase-orders"),link("supplier_id","Supplier","suppliers",true),text("reference","Reference"),text("title","Contract title",true),date("start_date","Start date"),date("end_date","End date"),money("amount","Contract amount",false).copy(defaultValue=null),currency,evidence),procurementRoles,initial="DRAFT",flow=reviewFlow(procurementRoles,setOf("DIRECTOR"))),
        r("assets","Equipment and assets","assets",listOf(award,link("purchase_order_id","Purchase order","purchase-orders"),text("asset_tag","Asset tag",true),area("description","Description",true),text("serial_number","Serial number"),text("location","Location",true),link("custodian_user_id","Custodian","users",true),date("acquired_date","Acquisition date"),money("acquisition_cost","Acquisition cost",false).copy(defaultValue=null),currency),procurementRoles,initial="ACTIVE",awardColumn="award_id"),
        r("laboratory-items","Laboratory register","laboratory_items",listOf(award,select("item_type","Item type",listOf("REAGENT","CONSUMABLE","EQUIPMENT"),"EQUIPMENT"),text("name","Item name",true),text("catalogue_or_asset_ref","Catalogue or asset reference"),GrantField("quantity","Quantity","decimal",defaultValue="0"),text("unit","Unit"),date("expiry_date","Expiry date"),date("calibration_due_date","Calibration due date"),date("maintenance_due_date","Maintenance due date")),labRoles,initial="ACTIVE",awardColumn="award_id"),
        r("maintenance","Maintenance and calibration","laboratory_maintenance",listOf(link("laboratory_item_id","Laboratory equipment","laboratory-items",true),select("activity_type","Activity",listOf("MAINTENANCE","CALIBRATION","REPAIR"),"MAINTENANCE"),date("scheduled_date","Scheduled date",true),date("completed_date","Completion date"),text("provider","Service provider"),url("certificate_storage_key","Certificate link"),area("notes","Notes")),labRoles,initial="SCHEDULED",flow=listOf(GrantTransition("COMPLETE","Record completed service",setOf("SCHEDULED"),"COMPLETED",labRoles,false,true))),
        r("compliance","Ethics and regulatory links","compliance_records",listOf(award,link("application_id","Related application","applications"),text("compliance_type","Compliance type",true),text("authority","External authority",true),text("reference","External reference"),date("approved_date","Approval date"),date("expiry_date","Expiry date"),date("renewal_due_date","Renewal due date"),evidence),governanceRoles,initial="PENDING",awardColumn="award_id",flow=listOf(GrantTransition("RECORD_APPROVAL","Record external approval",setOf("PENDING"),"APPROVED",governanceRoles,false,true))),
        r("reports","Technical reports","reports",listOf(award,text("report_type","Report type",true),date("period_start","Period start"),date("period_end","Period end"),date("due_date","Due date",true),owner,evidence),grantRoles+"RESEARCHER",initial="NOT_STARTED",awardColumn="award_id",flow=deliveryFlow(grantRoles+"RESEARCHER")),
        r("outputs","Research outputs","research_outputs",listOf(award,text("output_type","Output type",true),area("title","Output title",true),area("citation_or_reference","Citation or reference"),url("url","Public output link"),date("output_date","Output date")),grantRoles+"RESEARCHER",initial="RECORDED",awardColumn="award_id"),
        r("impact","Impact evidence","impact_records",listOf(award,text("impact_type","Impact type",true),text("title","Impact title",true),area("description","Description",true),url("evidence_storage_key","Evidence link"),date("impact_date","Impact date")),grantRoles+"RESEARCHER",initial="CLAIMED",awardColumn="award_id",flow=listOf(GrantTransition("VERIFY","Verify evidence",setOf("CLAIMED"),"VERIFIED",grantRoles,true,true))),
        r("closeout","Award closeout checklist","closeout_items",listOf(award,text("item_type","Checklist category",true),text("title","Requirement",true),text("responsible_role","Responsible role"),owner,date("due_date","Due date"),url("evidence_storage_key","Evidence link")),grantRoles,initial="PENDING",awardColumn="award_id",flow=listOf(GrantTransition("COMPLETE","Confirm completion",setOf("PENDING"),"COMPLETED",grantRoles,true,true))),
        r("support","Help and support","support_tickets",listOf(text("category","Category",true),select("priority","Priority",listOf("LOW","NORMAL","HIGH","URGENT"),"NORMAL"),text("subject","Subject",true),area("description","Description",true)),allBusiness,initial="NEW",creator="requester_id",readers=allBusiness),
        r("units","Organisation structure","organisation_units",listOf(text("code","Unit code",true,max=64),text("name","Unit name",true),link("parent_id","Parent unit","units"),select("unit_type","Unit type",listOf("INSTITUTION","DIVISION","UNIT","TEAM"),"UNIT")),setOf("ADMIN"),status=null,readers=allBusiness),
        r("themes","Research themes","research_themes",listOf(text("code","Theme code",true,max=60),text("name","Theme name",true,max=180)),setOf("ADMIN"),status=null,readers=allBusiness)
    ).associateBy { it.key }
    val narrativeFields=listOf(area("rationale","Problem and rationale",true),area("objectives","Objectives",true),area("approach","Proposed approach",true),area("institutionalFit","Institutional fit and capacity",true),area("team","Proposed team and partner contributions",true),area("expectedResults","Expected results and relevance",true),area("budgetSummary","Indicative budget and funding request",true),area("workplan","Workplan and milestones"),area("dataGovernance","Data and information governance"),area("ethics","Ethics and regulatory requirements"),area("dissemination","Dissemination and uptake"),GrantField("governanceReviewRequired","Governance review required","boolean",defaultValue="false"))
    fun requiredNarrative(type:String):Set<String> = when(type) {
        "SOI","EOI","LOI" -> setOf("rationale","objectives","institutionalFit","team","expectedResults","budgetSummary")
        "CONCEPT_NOTE" -> setOf("rationale","objectives","approach","institutionalFit","team","expectedResults","budgetSummary")
        else -> narrativeFields.filter { it.kind=="textarea" }.map { it.name }.toSet()
    }
}
