import {BarChart3,BriefcaseBusiness,CircleDollarSign,FlaskConical,Gauge,LockKeyhole,Settings,ShieldCheck,ShoppingCart,Target,UserRound,UsersRound} from "lucide-react";
export type Group={name:string;icon:any;items:string[]};
export const groups:Group[]=[
{name:"Executive",icon:Gauge,items:["Executive Overview","Portfolio Analytics","Pipeline Analytics"]},
{name:"Pre-Award",icon:Target,items:["Opportunity Intelligence","Eligibility & Fit","Applications","Proposal Workspace","Budget Builder","Internal Review","Approvals","Submissions"]},
{name:"Award Management",icon:BriefcaseBusiness,items:["Award Register","Award Setup","Contracts & Agreements","Partners & Subawards","Due Diligence","Amendments","Deliverables","Financial Monitoring","Risks & Issues"]},
{name:"Finance & Accounts",icon:CircleDollarSign,items:["Finance Dashboard","Award Budgets","Funds Received","Expenditure","Commitments","Budget vs Actual","Partner Advances","Financial Reporting","Financial Forecasts","Reconciliations","Financial Approvals","Financial Closeout"]},
{name:"Procurement",icon:ShoppingCart,items:["Procurement Dashboard","Procurement Plans","Requisitions","Purchase Orders","Suppliers & Due Diligence","Procurement Contracts","Equipment & Assets","Procurement Tracking"]},
{name:"Laboratory",icon:FlaskConical,items:["Laboratory Oversight","Laboratory Procurement","Reagents & Consumables","Laboratory Equipment","Maintenance & Calibration","Laboratory Compliance"]},
{name:"Research Governance",icon:ShieldCheck,items:["Ethics & Regulatory Links","Conflicts / Declarations","Compliance Calendar","Privacy & Information Governance","Legal & Contracts Review"]},
{name:"Performance",icon:BarChart3,items:["Reports","Outputs","Impact","Closeout"]},
{name:"People & Organisation",icon:UsersRound,items:["Researcher Profiles","Partner Directory","Funder Directory","NHRC Institutional Profile"]},
{name:"Personal",icon:UserRound,items:["My Work","Notifications","Calendar"]},
{name:"Administration",icon:Settings,items:["Users & Roles","Organisation Structure","Approval Rules","Delegations & Acting Roles","Workflow Configuration","Forms & Fields","Reference Data","Templates","Notification Rules","Calendar Rules","Data Import & Export","Records & Archives","Access Reviews","Help & Support","Audit Log","System Settings"]},
{name:"IT & Security",icon:LockKeyhole,items:["System Health","Service Monitoring","Integration Health","Job Monitor","Backup & Recovery","Security Centre","Security Events","Privileged Activity","Business Continuity","Environment Management","Superadmin Console"]}];
export const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8080";
export const endpoints:Record<string,string>={
"Portfolio Analytics":"/api/portfolio/ending",
"Pipeline Analytics":"/api/executive/pipeline",
"Opportunity Intelligence":"/api/opportunities",
"Eligibility & Fit":"/api/opportunities",
"Applications":"/api/applications",
"Proposal Workspace":"/api/applications",
"Budget Builder":"/api/applications",
"Internal Review":"/api/applications",
"Approvals":"/api/approvals",
"Submissions":"/api/pregrant/quality-checks",
"Award Register":"/api/awards",
"Award Setup":"/api/award-management/setup",
"Contracts & Agreements":"/api/award-management/contracts",
"Partners & Subawards":"/api/award-management/partners",
"Due Diligence":"/api/award-management/due-diligence",
"Amendments":"/api/award-management/amendments",
"Deliverables":"/api/award-management/deliverables",
"Financial Monitoring":"/api/finance/summary",
"Risks & Issues":"/api/award-management/risks",
"Finance Dashboard":"/api/finance/summary",
"Award Budgets":"/api/awards",
"Funds Received":"/api/finance/receipts",
"Expenditure":"/api/finance/expenditure",
"Commitments":"/api/finance/commitments",
"Budget vs Actual":"/api/awards",
"Partner Advances":"/api/finance/partner-advances",
"Financial Reporting":"/api/finance/operations/reports",
"Financial Forecasts":"/api/finance/operations/forecasts",
"Reconciliations":"/api/finance/operations/reconciliations",
"Financial Approvals":"/api/finance/operations/approvals",
"Financial Closeout":"/api/award-management/closeout",
"Procurement Dashboard":"/api/procurement/requisitions",
"Procurement Plans":"/api/procurement/plans",
"Requisitions":"/api/procurement/requisitions",
"Purchase Orders":"/api/procurement/purchase-orders",
"Suppliers & Due Diligence":"/api/procurement/suppliers",
"Procurement Contracts":"/api/procurement/contracts",
"Equipment & Assets":"/api/procurement/assets",
"Procurement Tracking":"/api/procurement/requisitions",
"Laboratory Oversight":"/api/laboratory/items",
"Laboratory Procurement":"/api/procurement/plans",
"Reagents & Consumables":"/api/laboratory/items?type=REAGENT",
"Laboratory Equipment":"/api/laboratory/items?type=EQUIPMENT",
"Maintenance & Calibration":"/api/laboratory/maintenance",
"Laboratory Compliance":"/api/laboratory/compliance",
"Ethics & Regulatory Links":"/api/governance/compliance",
"Conflicts / Declarations":"/api/governance/declarations",
"Compliance Calendar":"/api/governance/compliance",
"Legal & Contracts Review":"/api/contracts",
"Reports":"/api/performance/reports",
"Outputs":"/api/performance/outputs",
"Impact":"/api/performance/impact",
"Closeout":"/api/performance/closeout",
"Researcher Profiles":"/api/people/researchers",
"Partner Directory":"/api/people/partners",
"Funder Directory":"/api/people/funders",
"Calendar":"/api/calendar",
"Users & Roles":"/api/admin/users",
"Organisation Structure":"/api/organisation/units",
"Approval Rules":"/api/configuration/approval-rules",
"Delegations & Acting Roles":"/api/admin/delegations",
"Workflow Configuration":"/api/configuration/workflows",
"Forms & Fields":"/api/configuration/forms",
"Reference Data":"/api/admin/reference-data/themes",
"Templates":"/api/configuration/templates",
"Notification Rules":"/api/admin/reference-data/notification-rules",
"Calendar Rules":"/api/admin/reference-data/calendar-rules",
"Data Import & Export":"/api/admin/records/imports",
"Records & Archives":"/api/admin/records/retention",
"Access Reviews":"/api/admin/access-reviews",
"Help & Support":"/api/admin/support",
"Audit Log":"/api/admin/audit",
"System Settings":"/api/admin/settings",
"System Health":"/api/system/assurance",
"Service Monitoring":"/api/system/assurance",
"Integration Health":"/api/it/integrations",
"Backup & Recovery":"/api/it/backups",
"Security Centre":"/api/system/assurance",
"Security Events":"/api/it/security/events",
"Privileged Activity":"/api/it/security/privileged",
"Business Continuity":"/api/system/assurance",
"Environment Management":"/api/public/status",
"Superadmin Console":"/api/superadmin/features"
};
