import {BarChart3,BriefcaseBusiness,CircleDollarSign,FlaskConical,Gauge,LockKeyhole,Settings,ShieldCheck,ShoppingCart,Target,UserRound,UsersRound} from "lucide-react";
export type Group={name:string;icon:any;items:string[]};
export const groups:Group[]=[
{name:"Executive",icon:Gauge,items:["Executive Overview","Portfolio Analytics","Pipeline Analytics"]},
{name:"Pre-Award",icon:Target,items:["Opportunity Intelligence","Eligibility & Fit","Applications","Proposal Workspace","Budget Builder","Internal Review","Approvals","Submissions"]},
{name:"Award Management",icon:BriefcaseBusiness,items:["Award Register","Award Setup","Contracts & Agreements","Partners & Subawards","Due Diligence","Amendments","Deliverables","Financial Monitoring","Risks & Issues"]},
{name:"Finance & Accounts",icon:CircleDollarSign,items:["Finance Dashboard","Award Budgets","Funds Received","Expenditure","Commitments","Budget vs Actual","Partner Advances","Financial Reporting","Financial Forecasts","Reconciliations","Financial Approvals","Financial Closeout"]},
{name:"Procurement",icon:ShoppingCart,items:["Procurement Dashboard","Procurement Plans","Requisitions","Purchase Orders","Suppliers & Due Diligence","Procurement Contracts","Equipment & Assets","Procurement Tracking"]},
{name:"Laboratory",icon:FlaskConical,items:["Laboratory Oversight","Laboratory Procurement","Reagents & Consumables","Laboratory Equipment","Maintenance & Calibration","Laboratory Compliance"]},
{name:"Research Governance",icon:ShieldCheck,items:["Ethics & Regulatory Links","Conflicts / Declarations","Compliance Calendar","Privacy & Information Governance","Legal & Contracts Review"]},
{name:"Performance",icon:BarChart3,items:["Reports","Outputs","Impact","Closeout"]},
{name:"People & Organisation",icon:UsersRound,items:["Researcher Profiles","Partner Directory","Funder Directory","NHRC Institutional Profile"]},
{name:"Personal",icon:UserRound,items:["My Work","Notifications","Calendar"]},
{name:"Administration",icon:Settings,items:["Users & Roles","Organisation Structure","Approval Rules","Delegations & Acting Roles","Workflow Configuration","Forms & Fields","Reference Data","Templates","Notification Rules","Calendar Rules","Data Import & Export","Records & Archives","Access Reviews","Help & Support","Audit Log","System Settings"]},
{name:"IT & Security",icon:LockKeyhole,items:["System Health","Service Monitoring","Integration Health","Job Monitor","Backup & Recovery","Security Centre","Security Events","Privileged Activity","Business Continuity","Environment Management","Superadmin Console"]}];
export const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8080";
export const endpoints:Record<string,string>={"Opportunity Intelligence":"/api/opportunities","Eligibility & Fit":"/api/opportunities","Applications":"/api/applications","Proposal Workspace":"/api/applications","Budget Builder":"/api/applications","Internal Review":"/api/applications","Submissions":"/api/pregrant/quality-checks","Award Register":"/api/awards","Award Setup":"/api/awards","Financial Monitoring":"/api/finance/summary","Finance Dashboard":"/api/finance/summary","Award Budgets":"/api/awards","Funds Received":"/api/finance/receipts","Budget vs Actual":"/api/awards","Financial Forecasts":"/api/finance/summary","Procurement Dashboard":"/api/procurement/requisitions","Requisitions":"/api/procurement/requisitions","Procurement Tracking":"/api/procurement/requisitions","Laboratory Oversight":"/api/laboratory/items","Laboratory Procurement":"/api/laboratory/items","Reagents & Consumables":"/api/laboratory/items?type=REAGENT","Laboratory Equipment":"/api/laboratory/items?type=EQUIPMENT","Maintenance & Calibration":"/api/laboratory/items?type=EQUIPMENT","Users & Roles":"/api/admin/users","Audit Log":"/api/admin/audit","Security Events":"/api/operations/system-events","Privileged Activity":"/api/admin/audit","Backup & Recovery":"/api/operations/backups"};
