"use client";
import {useEffect,useMemo,useState} from "react";
import {ChevronDown,Menu} from "lucide-react";
import {api,groups} from "./config";
import Workspace from "./Workspace";
type Row=Record<string,any>;
export default function GrantsApp(){const[open,setOpen]=useState<string|null>(null),[active,setActive]=useState("Home"),[summary,setSummary]=useState<Row>({}),[mobile,setMobile]=useState(false);useEffect(()=>{fetch(api+"/api/dashboard/summary").then(r=>r.json()).then(setSummary).catch(()=>{})},[]);const parent=useMemo(()=>groups.find(g=>g.items.includes(active)),[active]);const go=(g:string,i:string)=>{setOpen(g);setActive(i);setMobile(false)};const home=()=>{setActive("Home");setOpen(null);setMobile(false)};return <><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><button className="brandhome" onClick={home}><span className="brandmark"><img src="/nhrc-logo.png" alt=""/></span></button><div><b>NHRC Grants</b><small>RESEARCH. ACCOUNTABILITY.</small></div></div><nav>{groups.map(g=>{const I=g.icon,e=open===g.name,a=parent?.name===g.name;return <div className={`navsection ${a?"activeSection":""}`} key={g.name}><button className={`navtoggle ${a?"activegroup":""}`} onClick={()=>setOpen(e?null:g.name)}><span className="groupname"><span className="groupico"><I/></span><span>{g.name}</span></span><ChevronDown className={e?"rotate":""} size={14}/></button><div className={`navitems ${e?"":"collapsed"}`}>{g.items.map(i=><button className={`navbtn ${active===i?"active":""}`} key={i} onClick={()=>go(g.name,i)}><span className="miniDot"/>{i}</button>)}</div></div>})}</nav><div className="sidefoot"><strong>NHRC Grants UAT</strong>Controlled demonstration records.<br/>No live donor submissions.<br/><br/>Institutional development environment.</div></aside><div className="shell"><header className="topbar"><div className="orgwrap"><button className="btn mobilemenu" onClick={()=>setMobile(!mobile)}><Menu size={16}/></button><div><div className="org">Navrongo Health Research Centre</div><small>Grants management and institutional oversight</small></div></div><div className="topright"><span className="statusline"><i/>UAT environment</span><div className="avatar">DR</div><div><b>Demonstration</b><small>No signed-in user</small></div></div></header><div className="demo"><strong>UAT / DEVELOPMENT</strong> Demonstration records only. Do not enter confidential or live grant information.</div><main className="main">{active==="Home"?<Landing s={summary} go={go}/>:<Workspace name={active} group={parent?.name||""} query="" go={go}/>}<div className="footnote">NHRC Grants institutional UAT. Demonstration records only. No live donor submission, financial posting or account security is connected.</div></main></div></>}
function Landing({s,go}:{s:Row;go:(g:string,i:string)=>void}){return <><section className="landinghero"><div className="eyebrow light">NHRC GRANTS</div><h1>Research funding, managed as one institutional lifecycle.</h1><p>Senior-level oversight and controlled workflows from opportunity discovery through proposal development, award management, compliance, reporting, closeout and impact.</p><div className="actions"><button className="btn primary" onClick={()=>go("Executive","Executive Overview")}>Open Executive Overview</button><button className="btn" onClick={()=>go("Personal","My Work")}>Open My Work</button></div></section><div className="stats homeStats"><Stat l="Opportunities" v={s.opportunities}/><Stat l="Applications" v={s.applications}/><Stat l="Active awards" v={s.activeAwards}/><Stat l="Reports due" v={s.reportsDue}/></div><div className="landinggrid">{groups.map(g=>{const I=g.icon;return <button className="landingcard" key={g.name} onClick={()=>go(g.name,g.items[0])}><span className="groupico large"><I/></span><h2>{g.name}</h2><p>{descs[g.name]||g.items.slice(0,4).join(", ")}</p><span className="tiny">{g.items.length} workspaces · Open section</span></button>})}</div></>}
function Stat({l,v}:{l:string;v:any}){return <div className="stat"><div className="label">{l}</div><div className="value">{v??"—"}</div><div className="note">Current UAT register</div></div>}
const descs:Record<string,string>={Executive:"Portfolio oversight, pipeline intelligence and management decisions.","Pre-Award":"Discover, assess, develop, review, approve and submit applications.","Award Management":"Activate awards, manage agreements, partners, finance, risks and obligations.","Finance & Accounts":"Control award finances, receipts, expenditure, advances and reporting.",Procurement:"Plan and track grant-funded purchasing, suppliers, contracts and assets.",Laboratory:"Coordinate grant-funded laboratory procurement, equipment and compliance.","Research Governance":"Track ethics, regulatory links, declarations and compliance dates.",Performance:"Reporting, research outputs, impact evidence and formal closeout.","People & Organisation":"Researcher, partner, funder and institutional master information.",Personal:"Your actions, notifications and consolidated grant calendar.",Administration:"Roles, approval rules, workflows, templates, records and audit controls.","IT & Security":"Service health, security, backups, integrations and privileged operations."};
