"use client";
import {useState} from "react";
import {X} from "lucide-react";
import {api} from "./config";
type Row=Record<string,any>;
export function Summary({data}:{data:Row}){return <div className="summaryGrid">{Object.entries(data).map(([k,v])=><div className="summaryTile" key={k}><span>{pretty(k)}</span><strong>{fmt(v,k)}</strong></div>)}</div>}
export function Register({rows,select}:{rows:Row[];select:(r:Row)=>void}){if(!rows.length)return <div className="empty"><h3>No matching records</h3><p>No governed records are currently available in this view.</p></div>;const pref=["reference","title","name","funder","stage","status","eligibility_status","deadline_at","currency","total_award","display_name","roles"];const keys=pref.filter(k=>rows.some(r=>k in r)).slice(0,7);const use=keys.length?keys:Object.keys(rows[0]).filter(k=>k!=="id").slice(0,7);return <div className="tableWrap"><table><thead><tr>{use.map(k=><th key={k}>{pretty(k)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} onClick={()=>select(r)}>{use.map(k=><td key={k}>{fmt(r[k],k)}</td>)}</tr>)}</tbody></table></div>}
export function Calendar({rows,name}:{rows:Row[];name:string}){return <div className="calendarGrid"><section className="panel"><h3>{name}</h3><div className="calendarDays">{["Mon","Tue","Wed","Thu","Fri"].map((d,i)=><div key={d}><b>{d}</b><span>{15+i} Sep</span></div>)}</div></section><section className="panel"><h3>Upcoming obligations</h3>{rows.length?rows.slice(0,5).map((r,i)=><div className="agenda" key={r.id||i}><span>{fmt(r.calibration_due_date||r.maintenance_due_date||r.deadline_at,"date")}</span><b>{r.name||r.title||r.reference}</b></div>):<p className="note">No dated records in this view.</p>}</section></div>}
export function Purpose({name,group}:{name:string;group:string}){const controls=purposeControls(name);return <div className="purposeGrid"><section className="panel"><span className="eyebrow">PURPOSE</span><h3>{name}</h3><p className="note">Dedicated {group} workspace retained from the approved v0.7 design. It is intentionally distinct from neighbouring registers.</p></section><section className="panel"><h3>Core controls</h3>{controls.map(x=><div className="check" key={x}><span>✓</span>{x}</div>)}</section><section className="panel"><h3>Operational state</h3><div className="stateBadge">Configured</div><p className="note">The database and service foundation for this domain is present. Actions are exposed only when their governed transaction is wired.</p></section></div>}
function purposeControls(n:string){if(n.includes("Contract")||n.includes("Agreement"))return["Agreement register","Version and status control","Key dates and obligations","Authorised document evidence"];if(n.includes("Due Diligence"))return["Entity assessment","Risk rating","Conditions and findings","Review / expiry date"];if(n.includes("Closeout"))return["Technical completion","Financial reconciliation","Asset / partner closure","Archive evidence"];if(n.includes("Security")||n.includes("Superadmin"))return["Restricted access","Privileged activity audit","Separation from business approval","Environment controls"];if(n.includes("Report")||n==="Outputs"||n==="Impact")return["Accountable owner","Due / output date","Evidence and status","Funder / institutional acceptance"];return["Role-based ownership","Search and filters","Traceable status","Audit history"]}
export function Drawer({row,close}:{row:Row;close:()=>void}){return <div className="drawerBackdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X size={15}/>Close</button><span className="eyebrow">RECORD DETAIL</span><h3>{row.title||row.name||row.reference||"Record"}</h3>{Object.entries(row).map(([k,v])=><div className="detail" key={k}><span>{pretty(k)}</span><b>{fmt(v,k)}</b></div>)}</aside></div>}
export function AddOpportunity({close,saved}:{close:()=>void;saved:()=>void}){const[title,setTitle]=useState(""),[deadline,setDeadline]=useState(""),[summary,setSummary]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:any){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(api+"/api/opportunities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,sourceType:"MANUAL",sourceReference:"UAT-MANUAL",summary,deadlineAt:deadline?new Date(deadline).toISOString():null})});if(!r.ok)throw new Error("Could not save opportunity");saved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <div className="drawerBackdrop"><aside className="drawer"><button className="close" onClick={close}><X size={15}/>Close</button><span className="eyebrow">PRE-AWARD</span><h3>Add funding opportunity</h3><form className="form" onSubmit={submit}><label>Opportunity title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Deadline<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label>Summary<textarea rows={6} value={summary} onChange={e=>setSummary(e.target.value)}/></label>{error&&<p className="errorText">{error}</p>}<button className="primary" disabled={busy}>{busy?"Saving…":"Save opportunity"}</button></form></aside></div>}
function pretty(k:string){return k.split("_").join(" ").replace(/\b\w/g,c=>c.toUpperCase())}function fmt(v:any,k:string){if(v===null||v===undefined||v==="")return "—";if(typeof v==="object")return Array.isArray(v)?v.join(", "):JSON.stringify(v);if(typeof v==="string"&&/(_at|date|deadline)/.test(k)){const d=new Date(v);if(!Number.isNaN(d.valueOf()))return d.toLocaleDateString("en-GB")}return String(v)}
