CREATE TABLE IF NOT EXISTS uat_seed_state (seed_key VARCHAR(100) PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now(), description TEXT);
DO $$
DECLARE nhrc UUID; grants UUID; finance UUID; procurement UUID; lab UUID; director UUID; grants_user UUID; researcher UUID; finance_user UUID; procurement_user UUID; lab_user UUID; f1 UUID; f2 UUID; rp UUID; opp1 UUID; opp2 UUID; app1 UUID; award1 UUID; partner1 UUID; award_partner1 UUID;
BEGIN
IF NOT EXISTS (SELECT 1 FROM uat_seed_state WHERE seed_key='UAT_V010') THEN
 SELECT id INTO nhrc FROM organisation_units WHERE code='NHRC';
 INSERT INTO organisation_units(code,name,parent_id,unit_type) VALUES ('GRANTS','Grants & Research Support',nhrc,'UNIT'),('FINANCE','Finance & Accounts',nhrc,'UNIT'),('PROC','Procurement',nhrc,'UNIT'),('LAB','Laboratory',nhrc,'UNIT'),('GOV','Research Governance',nhrc,'UNIT') ON CONFLICT (code) DO NOTHING;
 SELECT id INTO grants FROM organisation_units WHERE code='GRANTS'; SELECT id INTO finance FROM organisation_units WHERE code='FINANCE'; SELECT id INTO procurement FROM organisation_units WHERE code='PROC'; SELECT id INTO lab FROM organisation_units WHERE code='LAB';
 INSERT INTO users(email,display_name,organisation_unit_id,job_title) VALUES ('director.uat@nhrc.local','UAT Director',nhrc,'Director'),('grants.uat@nhrc.local','UAT Grants Officer',grants,'Grants Officer'),('researcher.uat@nhrc.local','UAT Principal Investigator',grants,'Principal Investigator'),('finance.uat@nhrc.local','UAT Finance Officer',finance,'Finance Officer'),('procurement.uat@nhrc.local','UAT Procurement Officer',procurement,'Procurement Officer'),('laboratory.uat@nhrc.local','UAT Laboratory Officer',lab,'Laboratory Officer') ON CONFLICT (email) DO NOTHING;
 SELECT id INTO director FROM users WHERE email='director.uat@nhrc.local'; SELECT id INTO grants_user FROM users WHERE email='grants.uat@nhrc.local'; SELECT id INTO researcher FROM users WHERE email='researcher.uat@nhrc.local'; SELECT id INTO finance_user FROM users WHERE email='finance.uat@nhrc.local'; SELECT id INTO procurement_user FROM users WHERE email='procurement.uat@nhrc.local'; SELECT id INTO lab_user FROM users WHERE email='laboratory.uat@nhrc.local';
 INSERT INTO user_roles(user_id,role_id,scope_type,scope_id) SELECT director,id,'INSTITUTION',nhrc FROM roles WHERE code='DIRECTOR' ON CONFLICT DO NOTHING; INSERT INTO user_roles(user_id,role_id,scope_type,scope_id) SELECT grants_user,id,'INSTITUTION',nhrc FROM roles WHERE code='GRANTS_OFFICER' ON CONFLICT DO NOTHING; INSERT INTO user_roles(user_id,role_id,scope_type,scope_id) SELECT researcher,id,'INSTITUTION',nhrc FROM roles WHERE code='RESEARCHER' ON CONFLICT DO NOTHING; INSERT INTO user_roles(user_id,role_id,scope_type,scope_id) SELECT finance_user,id,'INSTITUTION',nhrc FROM roles WHERE code='FINANCE_OFFICER' ON CONFLICT DO NOTHING; INSERT INTO user_roles(user_id,role_id,scope_type,scope_id) SELECT procurement_user,id,'INSTITUTION',nhrc FROM roles WHERE code='PROCUREMENT_OFFICER' ON CONFLICT DO NOTHING; INSERT INTO user_roles(user_id,role_id,scope_type,scope_id) SELECT lab_user,id,'INSTITUTION',nhrc FROM roles WHERE code='LABORATORY_OFFICER' ON CONFLICT DO NOTHING;
 INSERT INTO funders(name,country_code,website,active) VALUES ('UAT Global Health Foundation','GB','https://example.invalid/uat-foundation',true),('UAT International Research Council','US','https://example.invalid/uat-council',true) ON CONFLICT (name) DO NOTHING; SELECT id INTO f1 FROM funders WHERE name='UAT Global Health Foundation'; SELECT id INTO f2 FROM funders WHERE name='UAT International Research Council';
 INSERT INTO researcher_profiles(user_id,ORCID,expertise,career_stage,summary,active) VALUES(researcher,'0000-0000-0000-0000',ARRAY['population health','data science','implementation science'],'SENIOR','UAT profile only.',true) ON CONFLICT (user_id) DO NOTHING; SELECT id INTO rp FROM researcher_profiles WHERE user_id=researcher;
 INSERT INTO opportunities(funder_id,title,source_type,source_reference,url,deadline_at,status,eligibility_status,institutional_fit_score,summary,created_by) VALUES(f1,'UAT Climate and Population Health Innovation Award','MANUAL','UAT-OPP-001','https://example.invalid/uat-opp-001',now()+interval '42 days','OPEN','ELIGIBLE',88.0,'Demonstration opportunity for NHRC UAT only.',grants_user) RETURNING id INTO opp1;
 INSERT INTO opportunities(funder_id,title,source_type,source_reference,url,deadline_at,status,eligibility_status,institutional_fit_score,summary,created_by) VALUES(f2,'UAT Laboratory Systems Strengthening Call','MANUAL','UAT-OPP-002','https://example.invalid/uat-opp-002',now()+interval '18 days','OPEN','CONDITIONAL',76.0,'Demonstration laboratory opportunity for NHRC UAT only.',grants_user) RETURNING id INTO opp2;
 INSERT INTO opportunity_researcher_matches(opportunity_id,researcher_profile_id,fit_score,rationale,human_confirmed) VALUES(opp1,rp,91.0,'UAT match based on demonstration expertise.',true);
 INSERT INTO applications(opportunity_id,reference,title,lead_researcher_id,owner_user_id,stage,progress_percent,deadline_at) VALUES(opp1,'UAT-APP-2026-001','UAT Integrated Population Health Decision Support',researcher,grants_user,'PREPARATION',48,now()+interval '42 days') RETURNING id INTO app1;
 INSERT INTO application_stage_history(application_id,from_stage,to_stage,note,changed_by) VALUES(app1,'ACCEPTED','PREPARATION','UAT lifecycle demonstration.',researcher);
 INSERT INTO application_budget_lines(application_id,category,description,year_no,quantity,unit_cost,currency,funder_amount,nhrc_contribution,partner_amount) VALUES(app1,'Personnel','UAT research personnel',1,1,120000,'GBP',120000,10000,0),(app1,'Equipment','UAT analytical equipment',1,1,45000,'GBP',45000,0,0),(app1,'Travel','UAT field and dissemination travel',1,1,18000,'GBP',18000,0,0);
 INSERT INTO application_reviews(application_id,review_type,reviewer_id,status,comments) VALUES(app1,'FINANCE',finance_user,'PENDING','UAT finance clearance pending.'),(app1,'INTERNAL',grants_user,'PENDING','UAT internal review pending.');
 INSERT INTO awards(reference,title,funder_id,principal_investigator_id,status,currency,total_award,nhrc_allocation,partner_allocation,start_date,end_date) VALUES('UAT-AWD-2026-001','UAT Maternal and Child Health Systems Programme',f1,researcher,'ACTIVE','GBP',750000,525000,225000,current_date-120,current_date+610) RETURNING id INTO award1;
 INSERT INTO award_financial_positions(award_id,approved_budget,cash_received,expenditure,commitments,updated_at) VALUES(award1,525000,300000,168400,74200,now());
 INSERT INTO fund_receipts(award_id,instalment_no,expected_amount,expected_date,received_amount,received_date,currency,reference,verified_by,verified_at) VALUES(award1,1,300000,current_date-90,300000,current_date-92,'GBP','UAT-REC-001',finance_user,now()),(award1,2,225000,current_date+75,NULL,NULL,'GBP','UAT-REC-002',NULL,NULL);
 INSERT INTO expenditures(award_id,transaction_date,category,description,amount,currency,finance_reference,reconciled) VALUES(award1,current_date-30,'Personnel','UAT payroll expenditure',98500,'GBP','UAT-EXP-001',true),(award1,current_date-18,'Equipment','UAT equipment expenditure',69900,'GBP','UAT-EXP-002',true);
 INSERT INTO commitments(award_id,category,description,amount,currency,expected_date,status) VALUES(award1,'Laboratory','UAT reagent commitment',32200,'GBP',current_date+21,'OPEN'),(award1,'Services','UAT specialist services',42000,'GBP',current_date+45,'OPEN');
 INSERT INTO award_deliverables(award_id,deliverable_type,title,due_date,owner_user_id,status) VALUES(award1,'REPORT','UAT six-month technical report',current_date+24,researcher,'IN_PROGRESS'),(award1,'DATA','UAT curated analytical dataset',current_date+120,researcher,'NOT_STARTED');
 INSERT INTO award_risks(award_id,title,description,likelihood,impact,rating,owner_user_id,mitigation,status,review_date) VALUES(award1,'UAT procurement lead-time','Demonstration risk only.','MEDIUM','HIGH','HIGH',procurement_user,'Advance procurement planning.','OPEN',current_date+14);
 INSERT INTO reports(award_id,report_type,period_start,period_end,due_date,owner_user_id,status) VALUES(award1,'TECHNICAL',current_date-180,current_date,current_date+24,researcher,'IN_PROGRESS'),(award1,'FINANCIAL',current_date-180,current_date,current_date+24,finance_user,'NOT_STARTED');
 INSERT INTO compliance_records(award_id,compliance_type,authority,reference,status,approved_date,expiry_date,renewal_due_date) VALUES(award1,'ETHICS','UAT Ethics Authority','UAT-ETH-001','APPROVED',current_date-100,current_date+265,current_date+220);
 INSERT INTO partners(name,country_code,organisation_type,primary_contact_name,primary_contact_email,due_diligence_status,risk_rating) VALUES('UAT University Partner','GH','University','UAT Partner Contact','partner.uat@example.invalid','APPROVED','LOW') ON CONFLICT (name,country_code) DO NOTHING; SELECT id INTO partner1 FROM partners WHERE name='UAT University Partner' AND country_code='GH';
 INSERT INTO award_partners(award_id,partner_id,role,approved_allocation,currency,agreement_status) VALUES(award1,partner1,'Research Partner',125000,'GBP','ACTIVE') RETURNING id INTO award_partner1; INSERT INTO partner_advances(award_partner_id,amount_advanced,amount_accounted,currency,advanced_date,retirement_due_date,status) VALUES(award_partner1,50000,36250,'GBP',current_date-60,current_date+15,'OUTSTANDING');
 INSERT INTO suppliers(name,country_code,contact_email,due_diligence_status) VALUES('UAT Scientific Supplies Ltd','GH','supplier.uat@example.invalid','APPROVED') ON CONFLICT (name) DO NOTHING; INSERT INTO procurement_plans(award_id,item_description,category,estimated_amount,currency,planned_date,procurement_method,status,owner_user_id) VALUES(award1,'UAT laboratory cold-chain equipment','EQUIPMENT',58000,'GBP',current_date+30,'COMPETITIVE','PLANNED',procurement_user);
 INSERT INTO laboratory_items(award_id,item_type,name,catalogue_or_asset_ref,quantity,unit,expiry_date,status) VALUES(award1,'REAGENT','UAT diagnostic reagent pack','UAT-LAB-001',120,'packs',current_date+150,'ACTIVE'); INSERT INTO laboratory_items(award_id,item_type,name,catalogue_or_asset_ref,calibration_due_date,maintenance_due_date,status) VALUES(award1,'EQUIPMENT','UAT laboratory analyser','UAT-ASSET-001',current_date+45,current_date+75,'ACTIVE');
 INSERT INTO notifications(user_id,type,title,message,entity_type,entity_id) VALUES(researcher,'DEADLINE','UAT technical report due','Technical report is due in 24 days.','AWARD',award1),(finance_user,'FINANCE','UAT instalment expected','Next funder instalment is expected in 75 days.','AWARD',award1),(procurement_user,'RISK','UAT procurement risk review','High procurement lead-time risk requires review.','AWARD',award1);
 INSERT INTO uat_seed_state(seed_key,description) VALUES('UAT_V010','Controlled demonstration records for NHRC Grants UAT. Not production data.');
END IF; END $$;
